/* Generated by @palantir/pack.document-schema.type-gen@0.20.0 */

import type { ArtifactRid, DocumentId, MediaId, ObjectId, UserId } from "@palantir/pack.document-schema.model-types";

/**
 * A record containing all reference types
 */
export interface Document {
  readonly id: string;
  readonly docRef: DocumentId;
  readonly userRef: UserId;
  readonly objectRef: ObjectId;
  readonly mediaRef: MediaId;
  readonly artifactRef: ArtifactRid;
  readonly optionalDocRef?: DocumentId;
  readonly docRefArray: readonly DocumentId[];
  readonly userRefArray: readonly UserId[];
  readonly optionalArtifactRef?: ArtifactRid;
  readonly artifactRefArray: readonly ArtifactRid[];
}

