/* Generated by @palantir/pack.document-schema.type-gen@0.20.0 */

import type { ArtifactRef, DocumentRef, MediaRef, ObjectRef, UserRef } from "@palantir/pack.document-schema.model-types";

/**
 * A record containing all reference types
 */
export interface Document {
  readonly id: string;
  readonly docRef: DocumentRef;
  readonly userRef: UserRef;
  readonly objectRef: ObjectRef;
  readonly mediaRef: MediaRef;
  readonly artifactRef: ArtifactRef;
  readonly optionalDocRef?: DocumentRef;
  readonly docRefArray: readonly DocumentRef[];
  readonly userRefArray: readonly UserRef[];
  readonly optionalArtifactRef?: ArtifactRef;
  readonly artifactRefArray: readonly ArtifactRef[];
}

