/* Generated by @palantir/pack.document-schema.type-gen@0.2.0 */


/**
 * A node in the graph
 */
export interface ObjectNode {
  readonly x: number;
  readonly y: number;
  readonly object: string;
  readonly label?: string;
  readonly edges: readonly Edge[];
}

/**
 * A text box in the graph
 */
export interface TextBox {
  readonly x: number;
  readonly y: number;
  readonly text: string;
}

/**
 * An edge in the graph
 */
export interface Edge {
  readonly source: ObjectNode;
  readonly target: ObjectNode;
}

export interface NodeObject extends ObjectNode {
  readonly type: "object";
}

export interface NodeTextBox extends TextBox {
  readonly type: "textBox";
}

export type Node = NodeObject | NodeTextBox;

export function isNodeObject(value: Node): value is NodeObject {
  return value.type === "object";
}

export function isNodeTextBox(value: Node): value is NodeTextBox {
  return value.type === "textBox";
}

