/* Generated by @palantir/pack.document-schema.type-gen@0.12.0 */


/**
 * A person record
 */
export interface Person {
  readonly name: string;
  readonly age: number;
  readonly email?: string;
}

