prefer-workspace-packages: true
packages:
  - demos/*/*
  - packages/*
  - packages/*/*
catalog:
  "@babel/preset-typescript": ^7.28.5
  "@changesets/changelog-git": ^0.2.1
  "@osdk/api": ~2.5.2
  "@osdk/client": ~2.5.2
  "@osdk/foundry.admin": ~2.42.0
  "@osdk/foundry.pack": ~2.46.0
  "@osdk/oauth": ~1.4.0
  "@osdk/react": ~0.6.0
  "@osdk/shared.client2": ~1.0.0
  "@types/fs-extra": ^11.0.4
  "@types/node": ^20.19.17
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  "@types/yargs": ^17.0.35
  bun: ^1.3.3
  commander: ^14.0.0
  cometd: ^7.0.18
  conjure-client: ^2.15.0
  consola: ^3.4.2
  execa: ^9.6.1
  find-up: ^8.0.0
  fs-extra: ^11.3.2
  happy-dom: ^20.0.11
  prettier: ^3.7.3
  remeda: ^2.32.0
  rimraf: ^6.1.2
  tiny-invariant: ^1.3.3
  tslib: ^2.8.1
  tsx: ^4.20.6
  typescript: ^5.9.3
  vitest: ^4.0.14
  vitest-mock-extended: ^3.1.0
  yjs: ^13.6.27
  zod: ^4.1.13
onlyBuiltDependencies:
  - bun
  - dprint
  - esbuild
