/* Generated by @palantir/pack.document-schema.type-gen@0.8.0 */

import type {
  DocumentRef,
  Model,
  ModelData,
  RecordId,
  RecordRef,
} from '@palantir/pack.document-schema.model-types';
import type { DocumentModel, ShapeBoxModel } from './models.js';
import type { ShapeBox_v1 } from './types_v1.js';
import type { ShapeBoxUpdate_v1 } from './writeTypes_v1.js';
import type { ShapeBox_v2 } from './types_v2.js';
import type { ShapeBoxUpdate_v2 } from './writeTypes_v2.js';

export interface VersionedDocRef_v1 extends DocumentRef<DocumentModel> {
  readonly version: 1;
  updateRecord(
    ref: RecordRef<typeof ShapeBoxModel>,
    data: ShapeBoxUpdate_v1
  ): Promise<void>;
  updateRecord<M extends Model>(
    ref: RecordRef<M>,
    data: Partial<ModelData<M>>
  ): Promise<void>;
  setCollectionRecord(
    model: typeof ShapeBoxModel,
    id: RecordId,
    data: ShapeBox_v1
  ): Promise<void>;
  setCollectionRecord<M extends Model>(
    model: M,
    id: RecordId,
    data: ModelData<M>
  ): Promise<void>;
}

export interface VersionedDocRef_v2 extends DocumentRef<DocumentModel> {
  readonly version: 2;
  updateRecord(
    ref: RecordRef<typeof ShapeBoxModel>,
    data: ShapeBoxUpdate_v2
  ): Promise<void>;
  updateRecord<M extends Model>(
    ref: RecordRef<M>,
    data: Partial<ModelData<M>>
  ): Promise<void>;
  setCollectionRecord(
    model: typeof ShapeBoxModel,
    id: RecordId,
    data: ShapeBox_v2
  ): Promise<void>;
  setCollectionRecord<M extends Model>(
    model: M,
    id: RecordId,
    data: ModelData<M>
  ): Promise<void>;
}

export type VersionedDocRef = VersionedDocRef_v1 | VersionedDocRef_v2;

/** Narrow a DocumentRef to a version-discriminated type for type-safe writes. */
export function asVersioned(
  docRef: DocumentRef<DocumentModel>
): VersionedDocRef {
  return docRef as VersionedDocRef;
}

/**
 * Exhaustive version handler. TypeScript enforces that every supported
 * version has a corresponding handler — adding a new schema version
 * produces a compile error at every call site until handled.
 */
export function matchVersion<R>(
  doc: VersionedDocRef,
  handlers: {
    readonly 1: (doc: VersionedDocRef_v1) => R;
    readonly 2: (doc: VersionedDocRef_v2) => R;
  }
): R {
  return (handlers as Record<number, (doc: VersionedDocRef) => R>)[
    doc.version
  ]!(doc);
}
