/* Generated by @palantir/pack.document-schema.type-gen@0.8.0 */

export type ShapeBoxUpdate_v2 = {
  readonly left?: number;
  readonly right?: number;
  readonly top?: number;
  readonly bottom?: number;
  readonly fillColor?: string;
  readonly strokeColor?: string;
  readonly opacity?: number;
};
