/* Generated by @palantir/pack.document-schema.type-gen@0.8.0 */

/**
 * A box shape
 */
export interface ShapeBox_v1 {
  readonly left: number;
  readonly right: number;
  readonly top: number;
  readonly bottom: number;
  readonly color?: string;
}
