/* Generated by @palantir/pack.document-schema.type-gen@0.8.0 */

export type ShapeBoxUpdate_v1 = {
  readonly left?: number;
  readonly right?: number;
  readonly top?: number;
  readonly bottom?: number;
  readonly color?: string;
};
