/*
 * Copyright 2025 Palantir Technologies, Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import fs from "fs-extra";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const PACKAGE_NAME = "@palantir/pack.document-schema.type-gen";

// Walk up directories to find package.json (works for both src and build/esm locations)
function findPackageJson(startDir: string): string {
  let dir = startDir;
  while (dir !== path.dirname(dir)) {
    const packageJsonPath = path.join(dir, "package.json");
    if (fs.existsSync(packageJsonPath)) {
      const pkg = fs.readJsonSync(packageJsonPath) as { name?: string };
      if (pkg.name === PACKAGE_NAME) {
        return packageJsonPath;
      }
    }
    dir = path.dirname(dir);
  }
  throw new Error(`Could not find package.json for ${PACKAGE_NAME}`);
}

const packageJsonPath = findPackageJson(__dirname);
const { version } = fs.readJsonSync(packageJsonPath) as { version: string };

export const GENERATED_FILE_HEADER: string = `/* Generated by ${PACKAGE_NAME}@${version} */\n\n`;
