/* Generated by @palantir/pack.document-schema.type-gen@0.20.0 */

import type { DocumentSchema, RecordModel, UnionModel } from "@palantir/pack.document-schema.model-types";
import { Metadata } from "@palantir/pack.document-schema.model-types";
import type { MergeBounds, MergeNodeShape, MergeNodeShapeBox, MergeNodeShapeCircle, MergePoint, MergeSceneNode, MergeShapeBox, MergeShapeCircle } from "./types.js";
import { MergeBoundsSchema, MergeNodeShapeSchema, MergeNodeShapeBoxSchema, MergeNodeShapeCircleSchema, MergePointSchema, MergeSceneNodeSchema, MergeShapeBoxSchema, MergeShapeCircleSchema } from "./schema.js";

export interface MergeBoundsModel extends RecordModel<MergeBounds, typeof MergeBoundsSchema> {}
export const MergeBoundsModel: MergeBoundsModel = {
  __type: {} as MergeBounds,
  zodSchema: MergeBoundsSchema,
  [Metadata]: {
    name: "MergeBounds",
  },
};

export interface MergeNodeShapeModel extends UnionModel<MergeNodeShape, typeof MergeNodeShapeSchema> {}
export const MergeNodeShapeModel: MergeNodeShapeModel = {
  __type: {} as MergeNodeShape,
  zodSchema: MergeNodeShapeSchema,
  [Metadata]: {
    discriminant: "shapeType",
    name: "MergeNodeShape",
  },
};

export interface MergeNodeShapeBoxModel extends UnionModel<MergeNodeShapeBox, typeof MergeNodeShapeBoxSchema> {}
export const MergeNodeShapeBoxModel: MergeNodeShapeBoxModel = {
  __type: {} as MergeNodeShapeBox,
  zodSchema: MergeNodeShapeBoxSchema,
  [Metadata]: {
    discriminant: "shapeType",
    name: "MergeNodeShapeBox",
  },
};

export interface MergeNodeShapeCircleModel extends UnionModel<MergeNodeShapeCircle, typeof MergeNodeShapeCircleSchema> {}
export const MergeNodeShapeCircleModel: MergeNodeShapeCircleModel = {
  __type: {} as MergeNodeShapeCircle,
  zodSchema: MergeNodeShapeCircleSchema,
  [Metadata]: {
    discriminant: "shapeType",
    name: "MergeNodeShapeCircle",
  },
};

export interface MergePointModel extends RecordModel<MergePoint, typeof MergePointSchema> {}
export const MergePointModel: MergePointModel = {
  __type: {} as MergePoint,
  zodSchema: MergePointSchema,
  [Metadata]: {
    name: "MergePoint",
  },
};

export interface MergeSceneNodeModel extends RecordModel<MergeSceneNode, typeof MergeSceneNodeSchema> {}
export const MergeSceneNodeModel: MergeSceneNodeModel = {
  __type: {} as MergeSceneNode,
  zodSchema: MergeSceneNodeSchema,
  [Metadata]: {
    name: "MergeSceneNode",
  },
};

export interface MergeShapeBoxModel extends RecordModel<MergeShapeBox, typeof MergeShapeBoxSchema> {}
export const MergeShapeBoxModel: MergeShapeBoxModel = {
  __type: {} as MergeShapeBox,
  zodSchema: MergeShapeBoxSchema,
  [Metadata]: {
    name: "MergeShapeBox",
  },
};

export interface MergeShapeCircleModel extends RecordModel<MergeShapeCircle, typeof MergeShapeCircleSchema> {}
export const MergeShapeCircleModel: MergeShapeCircleModel = {
  __type: {} as MergeShapeCircle,
  zodSchema: MergeShapeCircleSchema,
  [Metadata]: {
    name: "MergeShapeCircle",
  },
};

export const DocumentModel = {
    MergeBounds: MergeBoundsModel,
    MergeNodeShape: MergeNodeShapeModel,
    MergeNodeShapeBox: MergeNodeShapeBoxModel,
    MergeNodeShapeCircle: MergeNodeShapeCircleModel,
    MergePoint: MergePointModel,
    MergeSceneNode: MergeSceneNodeModel,
    MergeShapeBox: MergeShapeBoxModel,
    MergeShapeCircle: MergeShapeCircleModel,
  [Metadata]: {
    version: 1,
  },
} as const satisfies DocumentSchema;

export type DocumentModel = typeof DocumentModel;
