/* Generated by @palantir/pack.document-schema.type-gen@0.20.0 */

import type { ZodType } from "zod";
import { z } from "zod";
import type { MergeBounds_v1, MergeNodeShape_v1, MergeNodeShape_v1Box, MergeNodeShape_v1Circle, MergePoint_v1, MergeSceneNode_v1, MergeShapeBox_v1, MergeShapeCircle_v1 } from "./types_v1.js";

export const MergeBoundsSchema_v1 = z.object({
  height: z.number(),
  width: z.number(),
  x: z.number(),
  y: z.number()
}).passthrough() satisfies ZodType<MergeBounds_v1>;

export const MergePointSchema_v1 = z.object({
  id: z.string(),
  x: z.number(),
  y: z.number()
}).passthrough() satisfies ZodType<MergePoint_v1>;

export const MergeSceneNodeSchema_v1 = z.object({
  bounds: z.lazy((): ZodType<MergeBounds_v1> => MergeBoundsSchema_v1),
  id: z.string(),
  points: z.array(z.lazy((): ZodType<MergePoint_v1> => MergePointSchema_v1)),
  shape: z.lazy((): ZodType<MergeNodeShape_v1> => MergeNodeShapeSchema_v1)
}).passthrough() satisfies ZodType<MergeSceneNode_v1>;

export const MergeShapeBoxSchema_v1 = z.object({
  items: z.array(z.lazy((): ZodType<MergePoint_v1> => MergePointSchema_v1)),
  label: z.string(),
  payload: z.string(),
  x: z.number(),
  y: z.number()
}).passthrough() satisfies ZodType<MergeShapeBox_v1>;

export const MergeShapeCircleSchema_v1 = z.object({
  items: z.array(z.unknown()),
  label: z.string().optional(),
  payload: z.unknown(),
  x: z.number(),
  y: z.number()
}).passthrough() satisfies ZodType<MergeShapeCircle_v1>;

export const MergeNodeShapeSchema_v1Box = MergeShapeBoxSchema_v1.extend({
  shapeType: z.literal("box")
}) satisfies ZodType<MergeNodeShape_v1Box>;

export const MergeNodeShapeSchema_v1Circle = MergeShapeCircleSchema_v1.extend({
  shapeType: z.literal("circle")
}) satisfies ZodType<MergeNodeShape_v1Circle>;

export const MergeNodeShapeSchema_v1 = z.discriminatedUnion("shapeType", [
  MergeNodeShapeSchema_v1Box,
  MergeNodeShapeSchema_v1Circle
]) satisfies ZodType<MergeNodeShape_v1>;

