/* Generated by @palantir/pack.document-schema.type-gen@0.20.0 */


/**
 * Nested bounds for a scene node.
 */
export interface MergeBounds_v1 {
  readonly height: number;
  readonly width: number;
  readonly x: number;
  readonly y: number;
}

/**
 * A point in a drawing.
 */
export interface MergePoint_v1 {
  readonly id: string;
  readonly x: number;
  readonly y: number;
}

/**
 * A scene node containing nested records, a union, and an array of records.
 */
export interface MergeSceneNode_v1 {
  readonly bounds: MergeBounds_v1;
  readonly id: string;
  readonly points: readonly MergePoint_v1[];
  readonly shape: MergeNodeShape_v1;
}

/**
 * A shape variant with stricter fields.
 */
export interface MergeShapeBox_v1 {
  readonly items: readonly MergePoint_v1[];
  readonly label: string;
  readonly payload: string;
  readonly x: number;
  readonly y: number;
}

/**
 * A permissive shape variant.
 */
export interface MergeShapeCircle_v1 {
  readonly items: readonly any[];
  readonly label?: string;
  readonly payload: any;
  readonly x: number;
  readonly y: number;
}

export interface MergeNodeShape_v1Box extends MergeShapeBox_v1 {
  readonly shapeType: "box";
}

export interface MergeNodeShape_v1Circle extends MergeShapeCircle_v1 {
  readonly shapeType: "circle";
}

export type MergeNodeShape_v1 = MergeNodeShape_v1Box | MergeNodeShape_v1Circle;

export function isMergeNodeShape_v1Box(value: MergeNodeShape_v1): value is MergeNodeShape_v1Box {
  return value.shapeType === "box";
}

export function isMergeNodeShape_v1Circle(value: MergeNodeShape_v1): value is MergeNodeShape_v1Circle {
  return value.shapeType === "circle";
}

