/* Generated by @palantir/pack.document-schema.type-gen@0.8.0 */

import { z } from 'zod';

export const ShapeBoxInternalSchema = z
  .object({
    bottom: z.number(),
    color: z.string().optional(),
    left: z.number(),
    right: z.number(),
    top: z.number(),
  })
  .passthrough();
