/* Generated by @palantir/pack.document-schema.type-gen@0.8.0 */

import type {
  MigrationRegistry,
  UnionMigrationRegistry,
} from '@palantir/pack.document-schema.model-types';

export const ShapeBoxMigrations: MigrationRegistry<'ShapeBox'> = {
  modelName: 'ShapeBox',
  allFields: {
    bottom: { type: { kind: 'primitive' } },
    color: { type: { kind: 'optional', inner: { kind: 'primitive' } } },
    left: { type: { kind: 'primitive' } },
    right: { type: { kind: 'primitive' } },
    top: { type: { kind: 'primitive' } },
  },
  steps: [],
};
