// ============================================================
// versions.ts
// ============================================================

/* Generated by @palantir/pack.document-schema.type-gen@0.14.0 */

export type SupportedVersions = 1;
export type LatestVersion = 1;
export type MinSupportedVersion = 1;
