// ============================================================
// versions.ts
// ============================================================

/* Generated by @palantir/pack.document-schema.type-gen@0.8.0 */

export type SupportedVersions = 1 | 2 | 3;
export type LatestVersion = 3;
export type MinSupportedVersion = 1;
