/* Generated by @palantir/pack.document-schema.type-gen@0.6.0 */

import { z } from 'zod';

export const FeatureSchema = z.object({
  enabled: z.boolean(),
  isPublic: z.boolean().optional(),
  flags: z.array(z.boolean()),
});
