/* Generated by @palantir/pack.document-schema.type-gen@0.2.0 */

import { z } from 'zod';

export const CatSchema = z.object({
  meow: z.string(),
});

export const DogSchema = z.object({
  bark: z.string(),
});

export const AnimalCatSchema = CatSchema.extend({
  kind: z.literal('cat'),
});

export const AnimalDogSchema = DogSchema.extend({
  kind: z.literal('dog'),
});

export const AnimalSchema = z.discriminatedUnion('kind', [
  AnimalCatSchema,
  AnimalDogSchema,
]);
