// ============================================================
// documentType.ts
// ============================================================

/* Generated by @palantir/pack.document-schema.type-gen@0.11.0 */

export const DOCUMENT_TYPE_NAME = 'Canvas Document';
export const DOCUMENT_TYPE_DESCRIPTION =
  'Schema generated from migration steps';
