/* Generated by @palantir/pack.document-schema.type-gen@0.14.0 */

export const DOCUMENT_TYPE_NAME = "Canvas Document Type";
export const DOCUMENT_TYPE_DESCRIPTION = "Document type description for demo canvas";
