/* Generated by @palantir/pack.document-schema.type-gen@0.19.0 */

import type { DocumentSchema, RecordModel, UnionModel, UpgradeFns } from "@palantir/pack.document-schema.model-types";
import { Metadata } from "@palantir/pack.document-schema.model-types";
import type { CanvasActivity, CanvasActivityShapeAdded, CanvasActivityShapeDeleted, CanvasActivityShapeUpdated, CursorPresence, FreehandStroke, NodeShape, NodeShapeBox, NodeShapeCircle, SelectionPresence, ShapeAddedActivity, ShapeBox, ShapeCircle, ShapeDeletedActivity, ShapeUpdatedActivity } from "./types.js";
import { CanvasActivitySchema, CanvasActivityShapeAddedSchema, CanvasActivityShapeDeletedSchema, CanvasActivityShapeUpdatedSchema, CursorPresenceSchema, FreehandStrokeSchema, NodeShapeSchema, NodeShapeBoxSchema, NodeShapeCircleSchema, SelectionPresenceSchema, ShapeAddedActivitySchema, ShapeBoxSchema, ShapeCircleSchema, ShapeDeletedActivitySchema, ShapeUpdatedActivitySchema } from "./schema.js";
import { ShapeBoxUpgrades, ShapeCircleUpgrades, ShapeAddedActivityUpgrades, ShapeDeletedActivityUpgrades, ShapeUpdatedActivityUpgrades, CursorPresenceUpgrades, SelectionPresenceUpgrades, FreehandStrokeUpgrades, NodeShapeUpgrades, CanvasActivityUpgrades } from "./_internal/upgrades.js";
import type { DocumentUpgradeFns } from "./_internal/upgradeFns.js";

export interface NodeShapeModel extends UnionModel<NodeShape, typeof NodeShapeSchema> {}
export const NodeShapeModel: NodeShapeModel = {
  __type: {} as NodeShape,
  zodSchema: NodeShapeSchema,
  [Metadata]: {
    discriminant: "shapeType",
    name: "NodeShape",
  },
};

export interface NodeShapeBoxModel extends UnionModel<NodeShapeBox, typeof NodeShapeBoxSchema> {}
export const NodeShapeBoxModel: NodeShapeBoxModel = {
  __type: {} as NodeShapeBox,
  zodSchema: NodeShapeBoxSchema,
  [Metadata]: {
    discriminant: "shapeType",
    name: "NodeShapeBox",
  },
};

export interface NodeShapeCircleModel extends UnionModel<NodeShapeCircle, typeof NodeShapeCircleSchema> {}
export const NodeShapeCircleModel: NodeShapeCircleModel = {
  __type: {} as NodeShapeCircle,
  zodSchema: NodeShapeCircleSchema,
  [Metadata]: {
    discriminant: "shapeType",
    name: "NodeShapeCircle",
  },
};

export interface ShapeBoxModel extends RecordModel<ShapeBox, typeof ShapeBoxSchema> {}
export const ShapeBoxModel: ShapeBoxModel = {
  __type: {} as ShapeBox,
  zodSchema: ShapeBoxSchema,
  [Metadata]: {
    name: "ShapeBox",
  },
};

export interface ShapeCircleModel extends RecordModel<ShapeCircle, typeof ShapeCircleSchema> {}
export const ShapeCircleModel: ShapeCircleModel = {
  __type: {} as ShapeCircle,
  zodSchema: ShapeCircleSchema,
  [Metadata]: {
    name: "ShapeCircle",
  },
};

export interface CanvasActivityModel extends UnionModel<CanvasActivity, typeof CanvasActivitySchema> {}
export const CanvasActivityModel: CanvasActivityModel = {
  __type: {} as CanvasActivity,
  zodSchema: CanvasActivitySchema,
  [Metadata]: {
    discriminant: "activityType",
    name: "CanvasActivity",
  },
};

export interface CanvasActivityShapeAddedModel extends UnionModel<CanvasActivityShapeAdded, typeof CanvasActivityShapeAddedSchema> {}
export const CanvasActivityShapeAddedModel: CanvasActivityShapeAddedModel = {
  __type: {} as CanvasActivityShapeAdded,
  zodSchema: CanvasActivityShapeAddedSchema,
  [Metadata]: {
    discriminant: "activityType",
    name: "CanvasActivityShapeAdded",
  },
};

export interface CanvasActivityShapeDeletedModel extends UnionModel<CanvasActivityShapeDeleted, typeof CanvasActivityShapeDeletedSchema> {}
export const CanvasActivityShapeDeletedModel: CanvasActivityShapeDeletedModel = {
  __type: {} as CanvasActivityShapeDeleted,
  zodSchema: CanvasActivityShapeDeletedSchema,
  [Metadata]: {
    discriminant: "activityType",
    name: "CanvasActivityShapeDeleted",
  },
};

export interface CanvasActivityShapeUpdatedModel extends UnionModel<CanvasActivityShapeUpdated, typeof CanvasActivityShapeUpdatedSchema> {}
export const CanvasActivityShapeUpdatedModel: CanvasActivityShapeUpdatedModel = {
  __type: {} as CanvasActivityShapeUpdated,
  zodSchema: CanvasActivityShapeUpdatedSchema,
  [Metadata]: {
    discriminant: "activityType",
    name: "CanvasActivityShapeUpdated",
  },
};

export interface ShapeAddedActivityModel extends RecordModel<ShapeAddedActivity, typeof ShapeAddedActivitySchema> {}
export const ShapeAddedActivityModel: ShapeAddedActivityModel = {
  __type: {} as ShapeAddedActivity,
  zodSchema: ShapeAddedActivitySchema,
  [Metadata]: {
    name: "ShapeAddedActivity",
  },
};

export interface ShapeDeletedActivityModel extends RecordModel<ShapeDeletedActivity, typeof ShapeDeletedActivitySchema> {}
export const ShapeDeletedActivityModel: ShapeDeletedActivityModel = {
  __type: {} as ShapeDeletedActivity,
  zodSchema: ShapeDeletedActivitySchema,
  [Metadata]: {
    name: "ShapeDeletedActivity",
  },
};

export interface ShapeUpdatedActivityModel extends RecordModel<ShapeUpdatedActivity, typeof ShapeUpdatedActivitySchema> {}
export const ShapeUpdatedActivityModel: ShapeUpdatedActivityModel = {
  __type: {} as ShapeUpdatedActivity,
  zodSchema: ShapeUpdatedActivitySchema,
  [Metadata]: {
    name: "ShapeUpdatedActivity",
  },
};

export interface CursorPresenceModel extends RecordModel<CursorPresence, typeof CursorPresenceSchema> {}
export const CursorPresenceModel: CursorPresenceModel = {
  __type: {} as CursorPresence,
  zodSchema: CursorPresenceSchema,
  [Metadata]: {
    name: "CursorPresence",
  },
};

export interface SelectionPresenceModel extends RecordModel<SelectionPresence, typeof SelectionPresenceSchema> {}
export const SelectionPresenceModel: SelectionPresenceModel = {
  __type: {} as SelectionPresence,
  zodSchema: SelectionPresenceSchema,
  [Metadata]: {
    name: "SelectionPresence",
  },
};

export interface FreehandStrokeModel extends RecordModel<FreehandStroke, typeof FreehandStrokeSchema> {}
export const FreehandStrokeModel: FreehandStrokeModel = {
  __type: {} as FreehandStroke,
  zodSchema: FreehandStrokeSchema,
  [Metadata]: {
    name: "FreehandStroke",
  },
};

/**
 * Construct the DocumentModel for this SDK, wiring in the typed forward
 * functions the runtime needs to materialize fields added past v1.
 */
export function DocumentModel(upgradeFns: DocumentUpgradeFns): DocumentSchema {
  return {
    NodeShape: NodeShapeModel,
    NodeShapeBox: NodeShapeBoxModel,
    NodeShapeCircle: NodeShapeCircleModel,
    ShapeBox: ShapeBoxModel,
    ShapeCircle: ShapeCircleModel,
    CanvasActivity: CanvasActivityModel,
    CanvasActivityShapeAdded: CanvasActivityShapeAddedModel,
    CanvasActivityShapeDeleted: CanvasActivityShapeDeletedModel,
    CanvasActivityShapeUpdated: CanvasActivityShapeUpdatedModel,
    ShapeAddedActivity: ShapeAddedActivityModel,
    ShapeDeletedActivity: ShapeDeletedActivityModel,
    ShapeUpdatedActivity: ShapeUpdatedActivityModel,
    CursorPresence: CursorPresenceModel,
    SelectionPresence: SelectionPresenceModel,
    FreehandStroke: FreehandStrokeModel,
    [Metadata]: {
      version: 3,
      minSupportedVersion: 1,
      upgrades: {
        ShapeBox: ShapeBoxUpgrades,
        ShapeCircle: ShapeCircleUpgrades,
        ShapeAddedActivity: ShapeAddedActivityUpgrades,
        ShapeDeletedActivity: ShapeDeletedActivityUpgrades,
        ShapeUpdatedActivity: ShapeUpdatedActivityUpgrades,
        CursorPresence: CursorPresenceUpgrades,
        SelectionPresence: SelectionPresenceUpgrades,
        FreehandStroke: FreehandStrokeUpgrades,
        NodeShape: NodeShapeUpgrades,
        CanvasActivity: CanvasActivityUpgrades,
      },
      upgradeFns: upgradeFns as unknown as UpgradeFns,
    },
  };
}

export type DocumentModel = ReturnType<typeof DocumentModel>;
