/* Generated by @palantir/pack.document-schema.type-gen@0.20.0 */

import type { ZodType } from "zod";
import { z } from "zod";
import type { CanvasActivity_v1, CanvasActivity_v1ShapeAdded, CanvasActivity_v1ShapeDeleted, CanvasActivity_v1ShapeUpdated, CursorPresence_v1, NodeShape_v1, NodeShape_v1Box, NodeShape_v1Circle, SelectionPresence_v1, ShapeAddedActivity_v1, ShapeBox_v1, ShapeCircle_v1, ShapeDeletedActivity_v1, ShapeUpdatedActivity_v1 } from "./types_v1.js";

export const ShapeBoxSchema_v1 = z.object({
  bottom: z.number(),
  left: z.number(),
  right: z.number(),
  top: z.number(),
  color: z.string().optional()
}).passthrough() satisfies ZodType<ShapeBox_v1>;

export const ShapeCircleSchema_v1 = z.object({
  bottom: z.number(),
  left: z.number(),
  right: z.number(),
  top: z.number(),
  color: z.string().optional()
}).passthrough() satisfies ZodType<ShapeCircle_v1>;

export const ShapeAddedActivitySchema_v1 = z.object({
  nodeId: z.string()
}).passthrough() satisfies ZodType<ShapeAddedActivity_v1>;

export const ShapeDeletedActivitySchema_v1 = z.object({
  nodeId: z.string()
}).passthrough() satisfies ZodType<ShapeDeletedActivity_v1>;

export const ShapeUpdatedActivitySchema_v1 = z.object({
  nodeId: z.string(),
  oldShape: z.lazy((): ZodType<NodeShape_v1> => NodeShapeSchema_v1),
  newShape: z.lazy((): ZodType<NodeShape_v1> => NodeShapeSchema_v1)
}).passthrough() satisfies ZodType<ShapeUpdatedActivity_v1>;

export const CursorPresenceSchema_v1 = z.object({
  x: z.number(),
  y: z.number()
}).passthrough() satisfies ZodType<CursorPresence_v1>;

export const SelectionPresenceSchema_v1 = z.object({
  selectedNodeIds: z.array(z.string())
}).passthrough() satisfies ZodType<SelectionPresence_v1>;

export const NodeShapeSchema_v1Box = ShapeBoxSchema_v1.extend({
  shapeType: z.literal("box")
}) satisfies ZodType<NodeShape_v1Box>;

export const NodeShapeSchema_v1Circle = ShapeCircleSchema_v1.extend({
  shapeType: z.literal("circle")
}) satisfies ZodType<NodeShape_v1Circle>;

export const NodeShapeSchema_v1 = z.discriminatedUnion("shapeType", [
  NodeShapeSchema_v1Box,
  NodeShapeSchema_v1Circle
]) satisfies ZodType<NodeShape_v1>;

export const CanvasActivitySchema_v1ShapeAdded = ShapeAddedActivitySchema_v1.extend({
  activityType: z.literal("shapeAdded")
}) satisfies ZodType<CanvasActivity_v1ShapeAdded>;

export const CanvasActivitySchema_v1ShapeDeleted = ShapeDeletedActivitySchema_v1.extend({
  activityType: z.literal("shapeDeleted")
}) satisfies ZodType<CanvasActivity_v1ShapeDeleted>;

export const CanvasActivitySchema_v1ShapeUpdated = ShapeUpdatedActivitySchema_v1.extend({
  activityType: z.literal("shapeUpdated")
}) satisfies ZodType<CanvasActivity_v1ShapeUpdated>;

export const CanvasActivitySchema_v1 = z.discriminatedUnion("activityType", [
  CanvasActivitySchema_v1ShapeAdded,
  CanvasActivitySchema_v1ShapeDeleted,
  CanvasActivitySchema_v1ShapeUpdated
]) satisfies ZodType<CanvasActivity_v1>;

