/* Generated by @palantir/pack.document-schema.type-gen@0.9.0 */

import type { ZodType } from "zod";
import { z } from "zod";
import type { ActivityEvent_v3, ActivityEvent_v3ShapeAdd, ActivityEvent_v3ShapeDelete, ActivityEvent_v3ShapeUpdate, ActivityShapeAddEvent_v3, ActivityShapeDeleteEvent_v3, ActivityShapeUpdateEvent_v3, FreehandStroke_v3, NodeShape_v3, NodeShape_v3Box, NodeShape_v3Circle, PresenceCursorEvent_v3, PresenceEvent_v3, PresenceEvent_v3Cursor, PresenceEvent_v3Selection, PresenceSelectionEvent_v3, ShapeBox_v3, ShapeCircle_v3 } from "./types_v3.js";

export const ActivityShapeAddEventSchema_v3 = z.object({
  nodeId: z.string()
}).passthrough() satisfies ZodType<ActivityShapeAddEvent_v3>;

export const ActivityShapeDeleteEventSchema_v3 = z.object({
  nodeId: z.string()
}).passthrough() satisfies ZodType<ActivityShapeDeleteEvent_v3>;

export const ActivityShapeUpdateEventSchema_v3 = z.object({
  nodeId: z.string(),
  oldShape: z.lazy((): ZodType<NodeShape_v3> => NodeShapeSchema_v3),
  newShape: z.lazy((): ZodType<NodeShape_v3> => NodeShapeSchema_v3)
}).passthrough() satisfies ZodType<ActivityShapeUpdateEvent_v3>;

export const PresenceCursorEventSchema_v3 = z.object({
  x: z.number(),
  y: z.number()
}).passthrough() satisfies ZodType<PresenceCursorEvent_v3>;

export const PresenceSelectionEventSchema_v3 = z.object({
  selectedNodeIds: z.array(z.string())
}).passthrough() satisfies ZodType<PresenceSelectionEvent_v3>;

export const ShapeBoxSchema_v3 = z.object({
  bottom: z.number(),
  left: z.number(),
  right: z.number(),
  top: z.number(),
  fillColor: z.string().optional(),
  strokeColor: z.string().optional(),
  opacity: z.number().optional()
}).passthrough() satisfies ZodType<ShapeBox_v3>;

export const ShapeCircleSchema_v3 = z.object({
  bottom: z.number(),
  left: z.number(),
  right: z.number(),
  top: z.number(),
  fillColor: z.string().optional(),
  strokeColor: z.string().optional(),
  opacity: z.number().optional()
}).passthrough() satisfies ZodType<ShapeCircle_v3>;

export const FreehandStrokeSchema_v3 = z.object({
  points: z.string(),
  color: z.string().optional()
}).passthrough() satisfies ZodType<FreehandStroke_v3>;

export const ActivityEventSchema_v3ShapeAdd = ActivityShapeAddEventSchema_v3.extend({
  eventType: z.literal("shapeAdd")
}) satisfies ZodType<ActivityEvent_v3ShapeAdd>;

export const ActivityEventSchema_v3ShapeDelete = ActivityShapeDeleteEventSchema_v3.extend({
  eventType: z.literal("shapeDelete")
}) satisfies ZodType<ActivityEvent_v3ShapeDelete>;

export const ActivityEventSchema_v3ShapeUpdate = ActivityShapeUpdateEventSchema_v3.extend({
  eventType: z.literal("shapeUpdate")
}) satisfies ZodType<ActivityEvent_v3ShapeUpdate>;

export const ActivityEventSchema_v3 = z.discriminatedUnion("eventType", [
  ActivityEventSchema_v3ShapeAdd,
  ActivityEventSchema_v3ShapeDelete,
  ActivityEventSchema_v3ShapeUpdate
]) satisfies ZodType<ActivityEvent_v3>;

export const NodeShapeSchema_v3Box = ShapeBoxSchema_v3.extend({
  shapeType: z.literal("box")
}) satisfies ZodType<NodeShape_v3Box>;

export const NodeShapeSchema_v3Circle = ShapeCircleSchema_v3.extend({
  shapeType: z.literal("circle")
}) satisfies ZodType<NodeShape_v3Circle>;

export const NodeShapeSchema_v3 = z.discriminatedUnion("shapeType", [
  NodeShapeSchema_v3Box,
  NodeShapeSchema_v3Circle
]) satisfies ZodType<NodeShape_v3>;

export const PresenceEventSchema_v3Cursor = PresenceCursorEventSchema_v3.extend({
  eventType: z.literal("cursor")
}) satisfies ZodType<PresenceEvent_v3Cursor>;

export const PresenceEventSchema_v3Selection = PresenceSelectionEventSchema_v3.extend({
  eventType: z.literal("selection")
}) satisfies ZodType<PresenceEvent_v3Selection>;

export const PresenceEventSchema_v3 = z.discriminatedUnion("eventType", [
  PresenceEventSchema_v3Cursor,
  PresenceEventSchema_v3Selection
]) satisfies ZodType<PresenceEvent_v3>;

