/* Generated by @palantir/pack.document-schema.type-gen@0.20.0 */

import type { ZodType } from "zod";
import { z } from "zod";
import type { CanvasActivity_v3, CanvasActivity_v3ShapeAdded, CanvasActivity_v3ShapeDeleted, CanvasActivity_v3ShapeUpdated, CursorPresence_v3, FreehandStroke_v3, NodeShape_v3, NodeShape_v3Box, NodeShape_v3Circle, SelectionPresence_v3, ShapeAddedActivity_v3, ShapeBox_v3, ShapeCircle_v3, ShapeDeletedActivity_v3, ShapeUpdatedActivity_v3 } from "./types_v3.js";

export const ShapeBoxSchema_v3 = z.object({
  bottom: z.number(),
  left: z.number(),
  right: z.number(),
  top: z.number(),
  fillColor: z.string().optional(),
  strokeColor: z.string().optional(),
  opacity: z.number()
}).passthrough() satisfies ZodType<ShapeBox_v3>;

export const ShapeCircleSchema_v3 = z.object({
  bottom: z.number(),
  left: z.number(),
  right: z.number(),
  top: z.number(),
  fillColor: z.string().optional(),
  strokeColor: z.string().optional(),
  opacity: z.number()
}).passthrough() satisfies ZodType<ShapeCircle_v3>;

export const ShapeAddedActivitySchema_v3 = z.object({
  nodeId: z.string()
}).passthrough() satisfies ZodType<ShapeAddedActivity_v3>;

export const ShapeDeletedActivitySchema_v3 = z.object({
  nodeId: z.string()
}).passthrough() satisfies ZodType<ShapeDeletedActivity_v3>;

export const ShapeUpdatedActivitySchema_v3 = z.object({
  nodeId: z.string(),
  oldShape: z.lazy((): ZodType<NodeShape_v3> => NodeShapeSchema_v3),
  newShape: z.lazy((): ZodType<NodeShape_v3> => NodeShapeSchema_v3),
  summary: z.string()
}).passthrough() satisfies ZodType<ShapeUpdatedActivity_v3>;

export const CursorPresenceSchema_v3 = z.object({
  x: z.number(),
  y: z.number()
}).passthrough() satisfies ZodType<CursorPresence_v3>;

export const SelectionPresenceSchema_v3 = z.object({
  selectedNodeIds: z.array(z.string())
}).passthrough() satisfies ZodType<SelectionPresence_v3>;

export const FreehandStrokeSchema_v3 = z.object({
  points: z.string(),
  color: z.string().optional()
}).passthrough() satisfies ZodType<FreehandStroke_v3>;

export const NodeShapeSchema_v3Box = ShapeBoxSchema_v3.extend({
  shapeType: z.literal("box")
}) satisfies ZodType<NodeShape_v3Box>;

export const NodeShapeSchema_v3Circle = ShapeCircleSchema_v3.extend({
  shapeType: z.literal("circle")
}) satisfies ZodType<NodeShape_v3Circle>;

export const NodeShapeSchema_v3 = z.discriminatedUnion("shapeType", [
  NodeShapeSchema_v3Box,
  NodeShapeSchema_v3Circle
]) satisfies ZodType<NodeShape_v3>;

export const CanvasActivitySchema_v3ShapeAdded = ShapeAddedActivitySchema_v3.extend({
  activityType: z.literal("shapeAdded")
}) satisfies ZodType<CanvasActivity_v3ShapeAdded>;

export const CanvasActivitySchema_v3ShapeDeleted = ShapeDeletedActivitySchema_v3.extend({
  activityType: z.literal("shapeDeleted")
}) satisfies ZodType<CanvasActivity_v3ShapeDeleted>;

export const CanvasActivitySchema_v3ShapeUpdated = ShapeUpdatedActivitySchema_v3.extend({
  activityType: z.literal("shapeUpdated")
}) satisfies ZodType<CanvasActivity_v3ShapeUpdated>;

export const CanvasActivitySchema_v3 = z.discriminatedUnion("activityType", [
  CanvasActivitySchema_v3ShapeAdded,
  CanvasActivitySchema_v3ShapeDeleted,
  CanvasActivitySchema_v3ShapeUpdated
]) satisfies ZodType<CanvasActivity_v3>;

