/* Generated by @palantir/pack.document-schema.type-gen@0.5.0 */

import type { ZodType } from "zod";
import { z } from "zod";
import type { ActivityEvent_v2, ActivityEvent_v2ShapeAdd, ActivityEvent_v2ShapeDelete, ActivityEvent_v2ShapeUpdate, ActivityShapeAddEvent_v2, ActivityShapeDeleteEvent_v2, ActivityShapeUpdateEvent_v2, NodeShape_v2, NodeShape_v2Box, NodeShape_v2Circle, PresenceCursorEvent_v2, PresenceEvent_v2, PresenceEvent_v2Cursor, PresenceEvent_v2Selection, PresenceSelectionEvent_v2, ShapeBox_v2, ShapeCircle_v2 } from "./types_v2.js";

export const ActivityShapeAddEventSchema_v2 = z.object({
  nodeId: z.string()
}) satisfies ZodType<ActivityShapeAddEvent_v2>;

export const ActivityShapeDeleteEventSchema_v2 = z.object({
  nodeId: z.string()
}) satisfies ZodType<ActivityShapeDeleteEvent_v2>;

export const ActivityShapeUpdateEventSchema_v2 = z.object({
  nodeId: z.string(),
  oldShape: z.lazy(() => NodeShapeSchema_v2) as any,
  newShape: z.lazy(() => NodeShapeSchema_v2) as any
}) satisfies ZodType<ActivityShapeUpdateEvent_v2>;

export const PresenceCursorEventSchema_v2 = z.object({
  x: z.number(),
  y: z.number()
}) satisfies ZodType<PresenceCursorEvent_v2>;

export const PresenceSelectionEventSchema_v2 = z.object({
  selectedNodeIds: z.array(z.string())
}) satisfies ZodType<PresenceSelectionEvent_v2>;

export const ShapeBoxSchema_v2 = z.object({
  bottom: z.number(),
  left: z.number(),
  right: z.number(),
  top: z.number(),
  fillColor: z.string().optional(),
  strokeColor: z.string().optional(),
  opacity: z.number()
}) satisfies ZodType<ShapeBox_v2>;

export const ShapeCircleSchema_v2 = z.object({
  bottom: z.number(),
  left: z.number(),
  right: z.number(),
  top: z.number(),
  fillColor: z.string().optional(),
  strokeColor: z.string().optional(),
  opacity: z.number()
}) satisfies ZodType<ShapeCircle_v2>;

export const ActivityEventSchema_v2ShapeAdd = ActivityShapeAddEventSchema_v2.extend({
  eventType: z.literal("shapeAdd")
}) satisfies ZodType<ActivityEvent_v2ShapeAdd>;

export const ActivityEventSchema_v2ShapeDelete = ActivityShapeDeleteEventSchema_v2.extend({
  eventType: z.literal("shapeDelete")
}) satisfies ZodType<ActivityEvent_v2ShapeDelete>;

export const ActivityEventSchema_v2ShapeUpdate = ActivityShapeUpdateEventSchema_v2.extend({
  eventType: z.literal("shapeUpdate")
}) satisfies ZodType<ActivityEvent_v2ShapeUpdate>;

export const ActivityEventSchema_v2 = z.discriminatedUnion("eventType", [
  ActivityEventSchema_v2ShapeAdd,
  ActivityEventSchema_v2ShapeDelete,
  ActivityEventSchema_v2ShapeUpdate
]) satisfies ZodType<ActivityEvent_v2>;

export const NodeShapeSchema_v2Box = ShapeBoxSchema_v2.extend({
  shapeType: z.literal("box")
}) satisfies ZodType<NodeShape_v2Box>;

export const NodeShapeSchema_v2Circle = ShapeCircleSchema_v2.extend({
  shapeType: z.literal("circle")
}) satisfies ZodType<NodeShape_v2Circle>;

export const NodeShapeSchema_v2 = z.discriminatedUnion("shapeType", [
  NodeShapeSchema_v2Box,
  NodeShapeSchema_v2Circle
]) satisfies ZodType<NodeShape_v2>;

export const PresenceEventSchema_v2Cursor = PresenceCursorEventSchema_v2.extend({
  eventType: z.literal("cursor")
}) satisfies ZodType<PresenceEvent_v2Cursor>;

export const PresenceEventSchema_v2Selection = PresenceSelectionEventSchema_v2.extend({
  eventType: z.literal("selection")
}) satisfies ZodType<PresenceEvent_v2Selection>;

export const PresenceEventSchema_v2 = z.discriminatedUnion("eventType", [
  PresenceEventSchema_v2Cursor,
  PresenceEventSchema_v2Selection
]) satisfies ZodType<PresenceEvent_v2>;

