/* Generated by @palantir/pack.document-schema.type-gen@0.13.0 */

import type { ZodType } from "zod";
import { z } from "zod";
import type { CanvasActivity_v2, CanvasActivity_v2ShapeAdded, CanvasActivity_v2ShapeDeleted, CanvasActivity_v2ShapeUpdated, CursorPresence_v2, NodeShape_v2, NodeShape_v2Box, NodeShape_v2Circle, SelectionPresence_v2, ShapeAddedActivity_v2, ShapeBox_v2, ShapeCircle_v2, ShapeDeletedActivity_v2, ShapeUpdatedActivity_v2 } from "./types_v2.js";

export const ShapeBoxSchema_v2 = z.object({
  bottom: z.number(),
  left: z.number(),
  right: z.number(),
  top: z.number(),
  fillColor: z.string().optional(),
  strokeColor: z.string().optional(),
  opacity: z.number().optional()
}).passthrough() satisfies ZodType<ShapeBox_v2>;

export const ShapeCircleSchema_v2 = z.object({
  bottom: z.number(),
  left: z.number(),
  right: z.number(),
  top: z.number(),
  fillColor: z.string().optional(),
  strokeColor: z.string().optional(),
  opacity: z.number().optional()
}).passthrough() satisfies ZodType<ShapeCircle_v2>;

export const ShapeAddedActivitySchema_v2 = z.object({
  nodeId: z.string()
}).passthrough() satisfies ZodType<ShapeAddedActivity_v2>;

export const ShapeDeletedActivitySchema_v2 = z.object({
  nodeId: z.string()
}).passthrough() satisfies ZodType<ShapeDeletedActivity_v2>;

export const ShapeUpdatedActivitySchema_v2 = z.object({
  nodeId: z.string(),
  oldShape: z.lazy((): ZodType<NodeShape_v2> => NodeShapeSchema_v2),
  newShape: z.lazy((): ZodType<NodeShape_v2> => NodeShapeSchema_v2)
}).passthrough() satisfies ZodType<ShapeUpdatedActivity_v2>;

export const CursorPresenceSchema_v2 = z.object({
  x: z.number(),
  y: z.number()
}).passthrough() satisfies ZodType<CursorPresence_v2>;

export const SelectionPresenceSchema_v2 = z.object({
  selectedNodeIds: z.array(z.string())
}).passthrough() satisfies ZodType<SelectionPresence_v2>;

export const NodeShapeSchema_v2Box = ShapeBoxSchema_v2.extend({
  shapeType: z.literal("box")
}) satisfies ZodType<NodeShape_v2Box>;

export const NodeShapeSchema_v2Circle = ShapeCircleSchema_v2.extend({
  shapeType: z.literal("circle")
}) satisfies ZodType<NodeShape_v2Circle>;

export const NodeShapeSchema_v2 = z.discriminatedUnion("shapeType", [
  NodeShapeSchema_v2Box,
  NodeShapeSchema_v2Circle
]) satisfies ZodType<NodeShape_v2>;

export const CanvasActivitySchema_v2ShapeAdded = ShapeAddedActivitySchema_v2.extend({
  activityType: z.literal("shapeAdded")
}) satisfies ZodType<CanvasActivity_v2ShapeAdded>;

export const CanvasActivitySchema_v2ShapeDeleted = ShapeDeletedActivitySchema_v2.extend({
  activityType: z.literal("shapeDeleted")
}) satisfies ZodType<CanvasActivity_v2ShapeDeleted>;

export const CanvasActivitySchema_v2ShapeUpdated = ShapeUpdatedActivitySchema_v2.extend({
  activityType: z.literal("shapeUpdated")
}) satisfies ZodType<CanvasActivity_v2ShapeUpdated>;

export const CanvasActivitySchema_v2 = z.discriminatedUnion("activityType", [
  CanvasActivitySchema_v2ShapeAdded,
  CanvasActivitySchema_v2ShapeDeleted,
  CanvasActivitySchema_v2ShapeUpdated
]) satisfies ZodType<CanvasActivity_v2>;

