/* Generated by @palantir/pack.document-schema.type-gen@0.5.0 */

import type { ZodType } from "zod";
import { z } from "zod";
import type { ActivityEvent_v1, ActivityEvent_v1ShapeAdd, ActivityEvent_v1ShapeDelete, ActivityEvent_v1ShapeUpdate, ActivityShapeAddEvent_v1, ActivityShapeDeleteEvent_v1, ActivityShapeUpdateEvent_v1, NodeShape_v1, NodeShape_v1Box, NodeShape_v1Circle, PresenceCursorEvent_v1, PresenceEvent_v1, PresenceEvent_v1Cursor, PresenceEvent_v1Selection, PresenceSelectionEvent_v1, ShapeBox_v1, ShapeCircle_v1 } from "./types_v1.js";

export const ActivityShapeAddEventSchema_v1 = z.object({
  nodeId: z.string()
}) satisfies ZodType<ActivityShapeAddEvent_v1>;

export const ActivityShapeDeleteEventSchema_v1 = z.object({
  nodeId: z.string()
}) satisfies ZodType<ActivityShapeDeleteEvent_v1>;

export const ActivityShapeUpdateEventSchema_v1 = z.object({
  nodeId: z.string(),
  oldShape: z.lazy(() => NodeShapeSchema_v1) as any,
  newShape: z.lazy(() => NodeShapeSchema_v1) as any
}) satisfies ZodType<ActivityShapeUpdateEvent_v1>;

export const PresenceCursorEventSchema_v1 = z.object({
  x: z.number(),
  y: z.number()
}) satisfies ZodType<PresenceCursorEvent_v1>;

export const PresenceSelectionEventSchema_v1 = z.object({
  selectedNodeIds: z.array(z.string())
}) satisfies ZodType<PresenceSelectionEvent_v1>;

export const ShapeBoxSchema_v1 = z.object({
  bottom: z.number(),
  left: z.number(),
  right: z.number(),
  top: z.number(),
  color: z.string().optional()
}) satisfies ZodType<ShapeBox_v1>;

export const ShapeCircleSchema_v1 = z.object({
  bottom: z.number(),
  left: z.number(),
  right: z.number(),
  top: z.number(),
  color: z.string().optional()
}) satisfies ZodType<ShapeCircle_v1>;

export const ActivityEventSchema_v1ShapeAdd = ActivityShapeAddEventSchema_v1.extend({
  eventType: z.literal("shapeAdd")
}) satisfies ZodType<ActivityEvent_v1ShapeAdd>;

export const ActivityEventSchema_v1ShapeDelete = ActivityShapeDeleteEventSchema_v1.extend({
  eventType: z.literal("shapeDelete")
}) satisfies ZodType<ActivityEvent_v1ShapeDelete>;

export const ActivityEventSchema_v1ShapeUpdate = ActivityShapeUpdateEventSchema_v1.extend({
  eventType: z.literal("shapeUpdate")
}) satisfies ZodType<ActivityEvent_v1ShapeUpdate>;

export const ActivityEventSchema_v1 = z.discriminatedUnion("eventType", [
  ActivityEventSchema_v1ShapeAdd,
  ActivityEventSchema_v1ShapeDelete,
  ActivityEventSchema_v1ShapeUpdate
]) satisfies ZodType<ActivityEvent_v1>;

export const NodeShapeSchema_v1Box = ShapeBoxSchema_v1.extend({
  shapeType: z.literal("box")
}) satisfies ZodType<NodeShape_v1Box>;

export const NodeShapeSchema_v1Circle = ShapeCircleSchema_v1.extend({
  shapeType: z.literal("circle")
}) satisfies ZodType<NodeShape_v1Circle>;

export const NodeShapeSchema_v1 = z.discriminatedUnion("shapeType", [
  NodeShapeSchema_v1Box,
  NodeShapeSchema_v1Circle
]) satisfies ZodType<NodeShape_v1>;

export const PresenceEventSchema_v1Cursor = PresenceCursorEventSchema_v1.extend({
  eventType: z.literal("cursor")
}) satisfies ZodType<PresenceEvent_v1Cursor>;

export const PresenceEventSchema_v1Selection = PresenceSelectionEventSchema_v1.extend({
  eventType: z.literal("selection")
}) satisfies ZodType<PresenceEvent_v1Selection>;

export const PresenceEventSchema_v1 = z.discriminatedUnion("eventType", [
  PresenceEventSchema_v1Cursor,
  PresenceEventSchema_v1Selection
]) satisfies ZodType<PresenceEvent_v1>;

