/* Generated by @palantir/pack.document-schema.type-gen@0.5.0 */

import type { DocumentRef, EditDescription, Model, ModelData, RecordRef } from "@palantir/pack.document-schema.model-types";
import type { ActivityShapeAddEventModel, ActivityShapeDeleteEventModel, ActivityShapeUpdateEventModel, NodeShapeModel, PresenceCursorEventModel, PresenceSelectionEventModel, ShapeBoxModel, ShapeCircleModel } from "./models.js";
import type { ActivityShapeAddEvent_v1, ActivityShapeDeleteEvent_v1, ActivityShapeUpdateEvent_v1, NodeShape_v1, PresenceCursorEvent_v1, PresenceSelectionEvent_v1, ShapeBox_v1, ShapeCircle_v1 } from "./types_v1.js";
import type { ActivityShapeAddEventUpdate_v1, ActivityShapeDeleteEventUpdate_v1, ActivityShapeUpdateEventUpdate_v1, PresenceCursorEventUpdate_v1, PresenceSelectionEventUpdate_v1, ShapeBoxUpdate_v1, ShapeCircleUpdate_v1 } from "./writeTypes_v1.js";
import type { ActivityShapeAddEvent_v2, ActivityShapeDeleteEvent_v2, ActivityShapeUpdateEvent_v2, NodeShape_v2, PresenceCursorEvent_v2, PresenceSelectionEvent_v2, ShapeBox_v2, ShapeCircle_v2 } from "./types_v2.js";
import type { ActivityShapeAddEventUpdate_v2, ActivityShapeDeleteEventUpdate_v2, ActivityShapeUpdateEventUpdate_v2, PresenceCursorEventUpdate_v2, PresenceSelectionEventUpdate_v2, ShapeBoxUpdate_v2, ShapeCircleUpdate_v2 } from "./writeTypes_v2.js";

export interface DocumentScopeBase {
  readonly version: number;
  readonly docRef: DocumentRef;
  withTransaction(fn: () => void, description?: EditDescription): void;
  deleteRecord<M extends Model>(ref: RecordRef<M>): void;
}

export interface DocumentScope_v1 extends DocumentScopeBase {
  readonly version: 1;
  updateRecord(ref: RecordRef<typeof ActivityShapeAddEventModel>, data: ActivityShapeAddEventUpdate_v1): void;
  setCollectionRecord(ref: RecordRef<typeof ActivityShapeAddEventModel>, data: ActivityShapeAddEvent_v1): void;
  updateRecord(ref: RecordRef<typeof ActivityShapeDeleteEventModel>, data: ActivityShapeDeleteEventUpdate_v1): void;
  setCollectionRecord(ref: RecordRef<typeof ActivityShapeDeleteEventModel>, data: ActivityShapeDeleteEvent_v1): void;
  updateRecord(ref: RecordRef<typeof ActivityShapeUpdateEventModel>, data: ActivityShapeUpdateEventUpdate_v1): void;
  setCollectionRecord(ref: RecordRef<typeof ActivityShapeUpdateEventModel>, data: ActivityShapeUpdateEvent_v1): void;
  updateRecord(ref: RecordRef<typeof PresenceCursorEventModel>, data: PresenceCursorEventUpdate_v1): void;
  setCollectionRecord(ref: RecordRef<typeof PresenceCursorEventModel>, data: PresenceCursorEvent_v1): void;
  updateRecord(ref: RecordRef<typeof PresenceSelectionEventModel>, data: PresenceSelectionEventUpdate_v1): void;
  setCollectionRecord(ref: RecordRef<typeof PresenceSelectionEventModel>, data: PresenceSelectionEvent_v1): void;
  updateRecord(ref: RecordRef<typeof NodeShapeModel>, data: Partial<NodeShape_v1>): void;
  setCollectionRecord(ref: RecordRef<typeof NodeShapeModel>, data: NodeShape_v1): void;
  updateRecord(ref: RecordRef<typeof ShapeBoxModel>, data: ShapeBoxUpdate_v1): void;
  setCollectionRecord(ref: RecordRef<typeof ShapeBoxModel>, data: ShapeBox_v1): void;
  updateRecord(ref: RecordRef<typeof ShapeCircleModel>, data: ShapeCircleUpdate_v1): void;
  setCollectionRecord(ref: RecordRef<typeof ShapeCircleModel>, data: ShapeCircle_v1): void;
  updateRecord<M extends Model>(ref: RecordRef<M>, data: Partial<ModelData<M>>): void;
  setCollectionRecord<M extends Model>(ref: RecordRef<M>, data: ModelData<M>): void;
}

export interface DocumentScope_v2 extends DocumentScopeBase {
  readonly version: 2;
  updateRecord(ref: RecordRef<typeof NodeShapeModel>, data: Partial<NodeShape_v2>): void;
  setCollectionRecord(ref: RecordRef<typeof NodeShapeModel>, data: NodeShape_v2): void;
  updateRecord(ref: RecordRef<typeof ShapeBoxModel>, data: ShapeBoxUpdate_v2): void;
  setCollectionRecord(ref: RecordRef<typeof ShapeBoxModel>, data: ShapeBox_v2): void;
  updateRecord(ref: RecordRef<typeof ShapeCircleModel>, data: ShapeCircleUpdate_v2): void;
  setCollectionRecord(ref: RecordRef<typeof ShapeCircleModel>, data: ShapeCircle_v2): void;
  updateRecord<M extends Model>(ref: RecordRef<M>, data: Partial<ModelData<M>>): void;
  setCollectionRecord<M extends Model>(ref: RecordRef<M>, data: ModelData<M>): void;
}

export type DocumentScope = DocumentScope_v1 | DocumentScope_v2;
