/* Generated by @palantir/pack.document-schema.type-gen@0.5.0 */


/**
 * An event representing the addition of a shape node.
 */
export interface ActivityShapeAddEvent_v3 {
  readonly nodeId: string;
}

/**
 * An event representing the deletion of a shape node.
 */
export interface ActivityShapeDeleteEvent_v3 {
  readonly nodeId: string;
}

/**
 * An event representing the update of a shape node.
 */
export interface ActivityShapeUpdateEvent_v3 {
  readonly nodeId: string;
  readonly oldShape: NodeShape_v3;
  readonly newShape: NodeShape_v3;
}

/**
 * Cursor position for remote user.
 */
export interface PresenceCursorEvent_v3 {
  readonly x: number;
  readonly y: number;
}

/**
 * Selected nodes for remote user.
 */
export interface PresenceSelectionEvent_v3 {
  readonly selectedNodeIds: readonly string[];
}

export interface ShapeBox_v3 {
  readonly bottom: number;
  readonly left: number;
  readonly right: number;
  readonly top: number;
  readonly fillColor?: string;
  readonly strokeColor?: string;
  readonly opacity: number;
}

export interface ShapeCircle_v3 {
  readonly bottom: number;
  readonly left: number;
  readonly right: number;
  readonly top: number;
  readonly fillColor?: string;
  readonly strokeColor?: string;
  readonly opacity: number;
}

/**
 * A freehand pen stroke stored as a JSON-encoded array of [x, y, pressure] tuples.
 */
export interface FreehandStroke_v3 {
  readonly points: string;
  readonly color?: string;
}

export interface ActivityEvent_v3ShapeAdd extends ActivityShapeAddEvent_v3 {
  readonly eventType: "shapeAdd";
}

export interface ActivityEvent_v3ShapeDelete extends ActivityShapeDeleteEvent_v3 {
  readonly eventType: "shapeDelete";
}

export interface ActivityEvent_v3ShapeUpdate extends ActivityShapeUpdateEvent_v3 {
  readonly eventType: "shapeUpdate";
}

export type ActivityEvent_v3 = ActivityEvent_v3ShapeAdd | ActivityEvent_v3ShapeDelete | ActivityEvent_v3ShapeUpdate;

export function isActivityEvent_v3ShapeAdd(value: ActivityEvent_v3): value is ActivityEvent_v3ShapeAdd {
  return value.eventType === "shapeAdd";
}

export function isActivityEvent_v3ShapeDelete(value: ActivityEvent_v3): value is ActivityEvent_v3ShapeDelete {
  return value.eventType === "shapeDelete";
}

export function isActivityEvent_v3ShapeUpdate(value: ActivityEvent_v3): value is ActivityEvent_v3ShapeUpdate {
  return value.eventType === "shapeUpdate";
}

export interface NodeShape_v3Box extends ShapeBox_v3 {
  readonly shapeType: "box";
}

export interface NodeShape_v3Circle extends ShapeCircle_v3 {
  readonly shapeType: "circle";
}

export type NodeShape_v3 = NodeShape_v3Box | NodeShape_v3Circle;

export function isNodeShape_v3Box(value: NodeShape_v3): value is NodeShape_v3Box {
  return value.shapeType === "box";
}

export function isNodeShape_v3Circle(value: NodeShape_v3): value is NodeShape_v3Circle {
  return value.shapeType === "circle";
}

export interface PresenceEvent_v3Cursor extends PresenceCursorEvent_v3 {
  readonly eventType: "cursor";
}

export interface PresenceEvent_v3Selection extends PresenceSelectionEvent_v3 {
  readonly eventType: "selection";
}

export type PresenceEvent_v3 = PresenceEvent_v3Cursor | PresenceEvent_v3Selection;

export function isPresenceEvent_v3Cursor(value: PresenceEvent_v3): value is PresenceEvent_v3Cursor {
  return value.eventType === "cursor";
}

export function isPresenceEvent_v3Selection(value: PresenceEvent_v3): value is PresenceEvent_v3Selection {
  return value.eventType === "selection";
}

