/* Generated by @palantir/pack.document-schema.type-gen@0.20.0 */


/**
 * A box.
 */
export interface ShapeBox_v1 {
  readonly bottom: number;
  readonly left: number;
  readonly right: number;
  readonly top: number;
  readonly color?: string;
}

/**
 * A circle.
 */
export interface ShapeCircle_v1 {
  readonly bottom: number;
  readonly left: number;
  readonly right: number;
  readonly top: number;
  readonly color?: string;
}

/**
 * Activity payload for a shape addition.
 */
export interface ShapeAddedActivity_v1 {
  readonly nodeId: string;
}

/**
 * Activity payload for a shape deletion.
 */
export interface ShapeDeletedActivity_v1 {
  readonly nodeId: string;
}

/**
 * Activity payload for a shape update.
 */
export interface ShapeUpdatedActivity_v1 {
  readonly nodeId: string;
  readonly oldShape: NodeShape_v1;
  readonly newShape: NodeShape_v1;
}

/**
 * Cursor position for a remote user.
 */
export interface CursorPresence_v1 {
  readonly x: number;
  readonly y: number;
}

/**
 * Selected shape ids for a remote user.
 */
export interface SelectionPresence_v1 {
  readonly selectedNodeIds: readonly string[];
}

export interface NodeShape_v1Box extends ShapeBox_v1 {
  readonly shapeType: "box";
}

export interface NodeShape_v1Circle extends ShapeCircle_v1 {
  readonly shapeType: "circle";
}

export type NodeShape_v1 = NodeShape_v1Box | NodeShape_v1Circle;

export function isNodeShape_v1Box(value: NodeShape_v1): value is NodeShape_v1Box {
  return value.shapeType === "box";
}

export function isNodeShape_v1Circle(value: NodeShape_v1): value is NodeShape_v1Circle {
  return value.shapeType === "circle";
}

export interface CanvasActivity_v1ShapeAdded extends ShapeAddedActivity_v1 {
  readonly activityType: "shapeAdded";
}

export interface CanvasActivity_v1ShapeDeleted extends ShapeDeletedActivity_v1 {
  readonly activityType: "shapeDeleted";
}

export interface CanvasActivity_v1ShapeUpdated extends ShapeUpdatedActivity_v1 {
  readonly activityType: "shapeUpdated";
}

export type CanvasActivity_v1 = CanvasActivity_v1ShapeAdded | CanvasActivity_v1ShapeDeleted | CanvasActivity_v1ShapeUpdated;

export function isCanvasActivity_v1ShapeAdded(value: CanvasActivity_v1): value is CanvasActivity_v1ShapeAdded {
  return value.activityType === "shapeAdded";
}

export function isCanvasActivity_v1ShapeDeleted(value: CanvasActivity_v1): value is CanvasActivity_v1ShapeDeleted {
  return value.activityType === "shapeDeleted";
}

export function isCanvasActivity_v1ShapeUpdated(value: CanvasActivity_v1): value is CanvasActivity_v1ShapeUpdated {
  return value.activityType === "shapeUpdated";
}

