/* Generated by @palantir/pack.document-schema.type-gen@0.14.0 */


export interface ShapeBox_v3 {
  readonly bottom: number;
  readonly left: number;
  readonly right: number;
  readonly top: number;
  readonly fillColor?: string;
  readonly strokeColor?: string;
  readonly opacity: number;
}

export interface ShapeCircle_v3 {
  readonly bottom: number;
  readonly left: number;
  readonly right: number;
  readonly top: number;
  readonly fillColor?: string;
  readonly strokeColor?: string;
  readonly opacity: number;
}

/**
 * Activity payload for a shape addition.
 */
export interface ShapeAddedActivity_v3 {
  readonly nodeId: string;
}

/**
 * Activity payload for a shape deletion.
 */
export interface ShapeDeletedActivity_v3 {
  readonly nodeId: string;
}

export interface ShapeUpdatedActivity_v3 {
  readonly nodeId: string;
  readonly oldShape: NodeShape_v3;
  readonly newShape: NodeShape_v3;
  readonly summary: string;
}

/**
 * Cursor position for a remote user.
 */
export interface CursorPresence_v3 {
  readonly x: number;
  readonly y: number;
}

/**
 * Selected shape ids for a remote user.
 */
export interface SelectionPresence_v3 {
  readonly selectedNodeIds: readonly string[];
}

/**
 * A freehand pen stroke stored as a JSON-encoded array of [x, y, pressure] tuples.
 */
export interface FreehandStroke_v3 {
  readonly points: string;
  readonly color?: string;
}

export interface NodeShape_v3Box extends ShapeBox_v3 {
  readonly shapeType: "box";
}

export interface NodeShape_v3Circle extends ShapeCircle_v3 {
  readonly shapeType: "circle";
}

export type NodeShape_v3 = NodeShape_v3Box | NodeShape_v3Circle;

export function isNodeShape_v3Box(value: NodeShape_v3): value is NodeShape_v3Box {
  return value.shapeType === "box";
}

export function isNodeShape_v3Circle(value: NodeShape_v3): value is NodeShape_v3Circle {
  return value.shapeType === "circle";
}

export interface CanvasActivity_v3ShapeAdded extends ShapeAddedActivity_v3 {
  readonly activityType: "shapeAdded";
}

export interface CanvasActivity_v3ShapeDeleted extends ShapeDeletedActivity_v3 {
  readonly activityType: "shapeDeleted";
}

export interface CanvasActivity_v3ShapeUpdated extends ShapeUpdatedActivity_v3 {
  readonly activityType: "shapeUpdated";
}

export type CanvasActivity_v3 = CanvasActivity_v3ShapeAdded | CanvasActivity_v3ShapeDeleted | CanvasActivity_v3ShapeUpdated;

export function isCanvasActivity_v3ShapeAdded(value: CanvasActivity_v3): value is CanvasActivity_v3ShapeAdded {
  return value.activityType === "shapeAdded";
}

export function isCanvasActivity_v3ShapeDeleted(value: CanvasActivity_v3): value is CanvasActivity_v3ShapeDeleted {
  return value.activityType === "shapeDeleted";
}

export function isCanvasActivity_v3ShapeUpdated(value: CanvasActivity_v3): value is CanvasActivity_v3ShapeUpdated {
  return value.activityType === "shapeUpdated";
}

