/* Generated by @palantir/pack.document-schema.type-gen@0.9.0 */


/**
 * An event representing the addition of a shape node.
 */
export interface ActivityShapeAddEvent_v1 {
  readonly nodeId: string;
}

/**
 * An event representing the deletion of a shape node.
 */
export interface ActivityShapeDeleteEvent_v1 {
  readonly nodeId: string;
}

/**
 * An event representing the update of a shape node.
 */
export interface ActivityShapeUpdateEvent_v1 {
  readonly nodeId: string;
  readonly oldShape: NodeShape_v1;
  readonly newShape: NodeShape_v1;
}

/**
 * Cursor position for remote user.
 */
export interface PresenceCursorEvent_v1 {
  readonly x: number;
  readonly y: number;
}

/**
 * Selected nodes for remote user.
 */
export interface PresenceSelectionEvent_v1 {
  readonly selectedNodeIds: readonly string[];
}

/**
 * A box.
 */
export interface ShapeBox_v1 {
  readonly bottom: number;
  readonly left: number;
  readonly right: number;
  readonly top: number;
  readonly color?: string;
}

/**
 * A circle.
 */
export interface ShapeCircle_v1 {
  readonly bottom: number;
  readonly left: number;
  readonly right: number;
  readonly top: number;
  readonly color?: string;
}

export interface ActivityEvent_v1ShapeAdd extends ActivityShapeAddEvent_v1 {
  readonly eventType: "shapeAdd";
}

export interface ActivityEvent_v1ShapeDelete extends ActivityShapeDeleteEvent_v1 {
  readonly eventType: "shapeDelete";
}

export interface ActivityEvent_v1ShapeUpdate extends ActivityShapeUpdateEvent_v1 {
  readonly eventType: "shapeUpdate";
}

export type ActivityEvent_v1 = ActivityEvent_v1ShapeAdd | ActivityEvent_v1ShapeDelete | ActivityEvent_v1ShapeUpdate;

export function isActivityEvent_v1ShapeAdd(value: ActivityEvent_v1): value is ActivityEvent_v1ShapeAdd {
  return value.eventType === "shapeAdd";
}

export function isActivityEvent_v1ShapeDelete(value: ActivityEvent_v1): value is ActivityEvent_v1ShapeDelete {
  return value.eventType === "shapeDelete";
}

export function isActivityEvent_v1ShapeUpdate(value: ActivityEvent_v1): value is ActivityEvent_v1ShapeUpdate {
  return value.eventType === "shapeUpdate";
}

export interface NodeShape_v1Box extends ShapeBox_v1 {
  readonly shapeType: "box";
}

export interface NodeShape_v1Circle extends ShapeCircle_v1 {
  readonly shapeType: "circle";
}

export type NodeShape_v1 = NodeShape_v1Box | NodeShape_v1Circle;

export function isNodeShape_v1Box(value: NodeShape_v1): value is NodeShape_v1Box {
  return value.shapeType === "box";
}

export function isNodeShape_v1Circle(value: NodeShape_v1): value is NodeShape_v1Circle {
  return value.shapeType === "circle";
}

export interface PresenceEvent_v1Cursor extends PresenceCursorEvent_v1 {
  readonly eventType: "cursor";
}

export interface PresenceEvent_v1Selection extends PresenceSelectionEvent_v1 {
  readonly eventType: "selection";
}

export type PresenceEvent_v1 = PresenceEvent_v1Cursor | PresenceEvent_v1Selection;

export function isPresenceEvent_v1Cursor(value: PresenceEvent_v1): value is PresenceEvent_v1Cursor {
  return value.eventType === "cursor";
}

export function isPresenceEvent_v1Selection(value: PresenceEvent_v1): value is PresenceEvent_v1Selection {
  return value.eventType === "selection";
}

