/* Generated by @palantir/pack.document-schema.type-gen@0.9.0 */


/**
 * An event representing the addition of a shape node.
 */
export interface ActivityShapeAddEvent_v2 {
  readonly nodeId: string;
}

/**
 * An event representing the deletion of a shape node.
 */
export interface ActivityShapeDeleteEvent_v2 {
  readonly nodeId: string;
}

/**
 * An event representing the update of a shape node.
 */
export interface ActivityShapeUpdateEvent_v2 {
  readonly nodeId: string;
  readonly oldShape: NodeShape_v2;
  readonly newShape: NodeShape_v2;
}

/**
 * Cursor position for remote user.
 */
export interface PresenceCursorEvent_v2 {
  readonly x: number;
  readonly y: number;
}

/**
 * Selected nodes for remote user.
 */
export interface PresenceSelectionEvent_v2 {
  readonly selectedNodeIds: readonly string[];
}

export interface ShapeBox_v2 {
  readonly bottom: number;
  readonly left: number;
  readonly right: number;
  readonly top: number;
  readonly fillColor?: string;
  readonly strokeColor?: string;
  readonly opacity?: number;
}

export interface ShapeCircle_v2 {
  readonly bottom: number;
  readonly left: number;
  readonly right: number;
  readonly top: number;
  readonly fillColor?: string;
  readonly strokeColor?: string;
  readonly opacity?: number;
}

export interface ActivityEvent_v2ShapeAdd extends ActivityShapeAddEvent_v2 {
  readonly eventType: "shapeAdd";
}

export interface ActivityEvent_v2ShapeDelete extends ActivityShapeDeleteEvent_v2 {
  readonly eventType: "shapeDelete";
}

export interface ActivityEvent_v2ShapeUpdate extends ActivityShapeUpdateEvent_v2 {
  readonly eventType: "shapeUpdate";
}

export type ActivityEvent_v2 = ActivityEvent_v2ShapeAdd | ActivityEvent_v2ShapeDelete | ActivityEvent_v2ShapeUpdate;

export function isActivityEvent_v2ShapeAdd(value: ActivityEvent_v2): value is ActivityEvent_v2ShapeAdd {
  return value.eventType === "shapeAdd";
}

export function isActivityEvent_v2ShapeDelete(value: ActivityEvent_v2): value is ActivityEvent_v2ShapeDelete {
  return value.eventType === "shapeDelete";
}

export function isActivityEvent_v2ShapeUpdate(value: ActivityEvent_v2): value is ActivityEvent_v2ShapeUpdate {
  return value.eventType === "shapeUpdate";
}

export interface NodeShape_v2Box extends ShapeBox_v2 {
  readonly shapeType: "box";
}

export interface NodeShape_v2Circle extends ShapeCircle_v2 {
  readonly shapeType: "circle";
}

export type NodeShape_v2 = NodeShape_v2Box | NodeShape_v2Circle;

export function isNodeShape_v2Box(value: NodeShape_v2): value is NodeShape_v2Box {
  return value.shapeType === "box";
}

export function isNodeShape_v2Circle(value: NodeShape_v2): value is NodeShape_v2Circle {
  return value.shapeType === "circle";
}

export interface PresenceEvent_v2Cursor extends PresenceCursorEvent_v2 {
  readonly eventType: "cursor";
}

export interface PresenceEvent_v2Selection extends PresenceSelectionEvent_v2 {
  readonly eventType: "selection";
}

export type PresenceEvent_v2 = PresenceEvent_v2Cursor | PresenceEvent_v2Selection;

export function isPresenceEvent_v2Cursor(value: PresenceEvent_v2): value is PresenceEvent_v2Cursor {
  return value.eventType === "cursor";
}

export function isPresenceEvent_v2Selection(value: PresenceEvent_v2): value is PresenceEvent_v2Selection {
  return value.eventType === "selection";
}

