/* Generated by @palantir/pack.document-schema.type-gen@0.3.0 */


/**
 * An event representing the addition of a shape node.
 */
export interface ActivityShapeAddEvent {
  readonly nodeId: string;
}

/**
 * An event representing the deletion of a shape node.
 */
export interface ActivityShapeDeleteEvent {
  readonly nodeId: string;
}

/**
 * An event representing the update of a shape node.
 */
export interface ActivityShapeUpdateEvent {
  readonly nodeId: string;
  readonly oldShape: NodeShape;
  readonly newShape: NodeShape;
}

/**
 * Cursor position for remote user.
 */
export interface PresenceCursorEvent {
  readonly x: number;
  readonly y: number;
}

/**
 * Selected nodes for remote user.
 */
export interface PresenceSelectionEvent {
  readonly selectedNodeIds: readonly string[];
}

/**
 * A box.
 */
export interface ShapeBox {
  readonly bottom: number;
  readonly left: number;
  readonly right: number;
  readonly top: number;
  readonly color?: string;
}

/**
 * A circle.
 */
export interface ShapeCircle {
  readonly bottom: number;
  readonly left: number;
  readonly right: number;
  readonly top: number;
  readonly color?: string;
}

export interface ActivityEventShapeAdd extends ActivityShapeAddEvent {
  readonly eventType: "shapeAdd";
}

export interface ActivityEventShapeDelete extends ActivityShapeDeleteEvent {
  readonly eventType: "shapeDelete";
}

export interface ActivityEventShapeUpdate extends ActivityShapeUpdateEvent {
  readonly eventType: "shapeUpdate";
}

export type ActivityEvent = ActivityEventShapeAdd | ActivityEventShapeDelete | ActivityEventShapeUpdate;

export function isActivityEventShapeAdd(value: ActivityEvent): value is ActivityEventShapeAdd {
  return value.eventType === "shapeAdd";
}

export function isActivityEventShapeDelete(value: ActivityEvent): value is ActivityEventShapeDelete {
  return value.eventType === "shapeDelete";
}

export function isActivityEventShapeUpdate(value: ActivityEvent): value is ActivityEventShapeUpdate {
  return value.eventType === "shapeUpdate";
}


export interface NodeShapeBox extends ShapeBox {
  readonly shapeType: "box";
}

export interface NodeShapeCircle extends ShapeCircle {
  readonly shapeType: "circle";
}

export type NodeShape = NodeShapeBox | NodeShapeCircle;

export function isNodeShapeBox(value: NodeShape): value is NodeShapeBox {
  return value.shapeType === "box";
}

export function isNodeShapeCircle(value: NodeShape): value is NodeShapeCircle {
  return value.shapeType === "circle";
}


export interface PresenceEventCursor extends PresenceCursorEvent {
  readonly eventType: "cursor";
}

export interface PresenceEventSelection extends PresenceSelectionEvent {
  readonly eventType: "selection";
}

export type PresenceEvent = PresenceEventCursor | PresenceEventSelection;

export function isPresenceEventCursor(value: PresenceEvent): value is PresenceEventCursor {
  return value.eventType === "cursor";
}

export function isPresenceEventSelection(value: PresenceEvent): value is PresenceEventSelection {
  return value.eventType === "selection";
}

