/* Generated by @palantir/pack.document-schema.type-gen@0.19.0 */


export interface ShapeBox_v2 {
  readonly bottom: number;
  readonly left: number;
  readonly right: number;
  readonly top: number;
  readonly fillColor?: string;
  readonly strokeColor?: string;
  readonly opacity: number;
}

export interface ShapeCircle_v2 {
  readonly bottom: number;
  readonly left: number;
  readonly right: number;
  readonly top: number;
  readonly fillColor?: string;
  readonly strokeColor?: string;
  readonly opacity: number;
}

/**
 * Activity payload for a shape addition.
 */
export interface ShapeAddedActivity_v2 {
  readonly nodeId: string;
}

/**
 * Activity payload for a shape deletion.
 */
export interface ShapeDeletedActivity_v2 {
  readonly nodeId: string;
}

/**
 * Activity payload for a shape update.
 */
export interface ShapeUpdatedActivity_v2 {
  readonly nodeId: string;
  readonly oldShape: NodeShape_v2;
  readonly newShape: NodeShape_v2;
}

/**
 * Cursor position for a remote user.
 */
export interface CursorPresence_v2 {
  readonly x: number;
  readonly y: number;
}

/**
 * Selected shape ids for a remote user.
 */
export interface SelectionPresence_v2 {
  readonly selectedNodeIds: readonly string[];
}

export interface NodeShape_v2Box extends ShapeBox_v2 {
  readonly shapeType: "box";
}

export interface NodeShape_v2Circle extends ShapeCircle_v2 {
  readonly shapeType: "circle";
}

export type NodeShape_v2 = NodeShape_v2Box | NodeShape_v2Circle;

export function isNodeShape_v2Box(value: NodeShape_v2): value is NodeShape_v2Box {
  return value.shapeType === "box";
}

export function isNodeShape_v2Circle(value: NodeShape_v2): value is NodeShape_v2Circle {
  return value.shapeType === "circle";
}

export interface CanvasActivity_v2ShapeAdded extends ShapeAddedActivity_v2 {
  readonly activityType: "shapeAdded";
}

export interface CanvasActivity_v2ShapeDeleted extends ShapeDeletedActivity_v2 {
  readonly activityType: "shapeDeleted";
}

export interface CanvasActivity_v2ShapeUpdated extends ShapeUpdatedActivity_v2 {
  readonly activityType: "shapeUpdated";
}

export type CanvasActivity_v2 = CanvasActivity_v2ShapeAdded | CanvasActivity_v2ShapeDeleted | CanvasActivity_v2ShapeUpdated;

export function isCanvasActivity_v2ShapeAdded(value: CanvasActivity_v2): value is CanvasActivity_v2ShapeAdded {
  return value.activityType === "shapeAdded";
}

export function isCanvasActivity_v2ShapeDeleted(value: CanvasActivity_v2): value is CanvasActivity_v2ShapeDeleted {
  return value.activityType === "shapeDeleted";
}

export function isCanvasActivity_v2ShapeUpdated(value: CanvasActivity_v2): value is CanvasActivity_v2ShapeUpdated {
  return value.activityType === "shapeUpdated";
}

