/* Generated by @palantir/pack.document-schema.type-gen@0.5.0 */

import type { DocumentRef, EditDescription, Model, ModelData, RecordCollectionRef, RecordId, RecordRef } from "@palantir/pack.document-schema.model-types";
import { getMetadata } from "@palantir/pack.document-schema.model-types";
import type { DocumentModel, ActivityEventModel, ActivityShapeAddEventModel, ActivityShapeDeleteEventModel, ActivityShapeUpdateEventModel, NodeShapeModel, PresenceCursorEventModel, PresenceEventModel, PresenceSelectionEventModel, ShapeBoxModel, ShapeCircleModel } from "./models.js";
import type { ActivityEvent_v1, ActivityShapeAddEvent_v1, ActivityShapeDeleteEvent_v1, ActivityShapeUpdateEvent_v1, NodeShape_v1, PresenceCursorEvent_v1, PresenceEvent_v1, PresenceSelectionEvent_v1, ShapeBox_v1, ShapeCircle_v1 } from "./types_v1.js";
import type { ActivityShapeAddEventUpdate_v1, ActivityShapeDeleteEventUpdate_v1, ActivityShapeUpdateEventUpdate_v1, PresenceCursorEventUpdate_v1, PresenceSelectionEventUpdate_v1, ShapeBoxUpdate_v1, ShapeCircleUpdate_v1 } from "./writeTypes_v1.js";
import type { ActivityEvent_v2, ActivityShapeAddEvent_v2, ActivityShapeDeleteEvent_v2, ActivityShapeUpdateEvent_v2, NodeShape_v2, PresenceCursorEvent_v2, PresenceEvent_v2, PresenceSelectionEvent_v2, ShapeBox_v2, ShapeCircle_v2 } from "./types_v2.js";
import type { ActivityShapeAddEventUpdate_v2, ActivityShapeDeleteEventUpdate_v2, ActivityShapeUpdateEventUpdate_v2, PresenceCursorEventUpdate_v2, PresenceSelectionEventUpdate_v2, ShapeBoxUpdate_v2, ShapeCircleUpdate_v2 } from "./writeTypes_v2.js";
import type { SupportedVersions } from "./versions.js";

interface VersionedDocRefBase {
  /** The underlying DocumentRef for framework hooks (useRecords, onPresence, etc.). */
  readonly ref: DocumentRef<DocumentModel>;
  withTransaction(fn: () => void, description?: EditDescription): void;
  deleteRecord<M extends Model>(ref: RecordRef<M>): void;
}

export interface VersionedDocRef_v1 extends VersionedDocRefBase {
  readonly version: 1;
  updateRecord(ref: RecordRef<typeof ActivityEventModel>, data: Partial<ActivityEvent_v1>): void;
  updateRecord(ref: RecordRef<typeof ActivityShapeAddEventModel>, data: ActivityShapeAddEventUpdate_v1): void;
  updateRecord(ref: RecordRef<typeof ActivityShapeDeleteEventModel>, data: ActivityShapeDeleteEventUpdate_v1): void;
  updateRecord(ref: RecordRef<typeof ActivityShapeUpdateEventModel>, data: ActivityShapeUpdateEventUpdate_v1): void;
  updateRecord(ref: RecordRef<typeof NodeShapeModel>, data: Partial<NodeShape_v1>): void;
  updateRecord(ref: RecordRef<typeof PresenceCursorEventModel>, data: PresenceCursorEventUpdate_v1): void;
  updateRecord(ref: RecordRef<typeof PresenceEventModel>, data: Partial<PresenceEvent_v1>): void;
  updateRecord(ref: RecordRef<typeof PresenceSelectionEventModel>, data: PresenceSelectionEventUpdate_v1): void;
  updateRecord(ref: RecordRef<typeof ShapeBoxModel>, data: ShapeBoxUpdate_v1): void;
  updateRecord(ref: RecordRef<typeof ShapeCircleModel>, data: ShapeCircleUpdate_v1): void;
  updateRecord<M extends Model>(ref: RecordRef<M>, data: Partial<ModelData<M>>): void;
  setCollectionRecord(model: typeof ActivityEventModel, id: RecordId, data: ActivityEvent_v1): void;
  setCollectionRecord(model: typeof ActivityShapeAddEventModel, id: RecordId, data: ActivityShapeAddEvent_v1): void;
  setCollectionRecord(model: typeof ActivityShapeDeleteEventModel, id: RecordId, data: ActivityShapeDeleteEvent_v1): void;
  setCollectionRecord(model: typeof ActivityShapeUpdateEventModel, id: RecordId, data: ActivityShapeUpdateEvent_v1): void;
  setCollectionRecord(model: typeof NodeShapeModel, id: RecordId, data: NodeShape_v1): void;
  setCollectionRecord(model: typeof PresenceCursorEventModel, id: RecordId, data: PresenceCursorEvent_v1): void;
  setCollectionRecord(model: typeof PresenceEventModel, id: RecordId, data: PresenceEvent_v1): void;
  setCollectionRecord(model: typeof PresenceSelectionEventModel, id: RecordId, data: PresenceSelectionEvent_v1): void;
  setCollectionRecord(model: typeof ShapeBoxModel, id: RecordId, data: ShapeBox_v1): void;
  setCollectionRecord(model: typeof ShapeCircleModel, id: RecordId, data: ShapeCircle_v1): void;
  setCollectionRecord<M extends Model>(model: M, id: RecordId, data: ModelData<M>): void;
}

export interface VersionedDocRef_v2 extends VersionedDocRefBase {
  readonly version: 2;
  updateRecord(ref: RecordRef<typeof NodeShapeModel>, data: Partial<NodeShape_v2>): void;
  updateRecord(ref: RecordRef<typeof ShapeBoxModel>, data: ShapeBoxUpdate_v2): void;
  updateRecord(ref: RecordRef<typeof ShapeCircleModel>, data: ShapeCircleUpdate_v2): void;
  updateRecord<M extends Model>(ref: RecordRef<M>, data: Partial<ModelData<M>>): void;
  setCollectionRecord(model: typeof NodeShapeModel, id: RecordId, data: NodeShape_v2): void;
  setCollectionRecord(model: typeof ShapeBoxModel, id: RecordId, data: ShapeBox_v2): void;
  setCollectionRecord(model: typeof ShapeCircleModel, id: RecordId, data: ShapeCircle_v2): void;
  setCollectionRecord<M extends Model>(model: M, id: RecordId, data: ModelData<M>): void;
}

export type VersionedDocRef = VersionedDocRef_v1 | VersionedDocRef_v2;

/**
 * Wrap a DocumentRef in a version-aware VersionedDocRef.
 * @param version - Explicit version override. When omitted the version is
 *   read from the schema metadata (latest).
 */
export function createVersionedDocRef(
  docRef: DocumentRef<DocumentModel>,
  version?: SupportedVersions,
): VersionedDocRef {
  const resolvedVersion = version ?? getMetadata(docRef.schema).version as SupportedVersions;
  return {
    version: resolvedVersion,
    ref: docRef,
    withTransaction: (fn: () => void, description?: EditDescription) =>
      docRef.withTransaction(fn, description),
    updateRecord: (recordRef: RecordRef, data: unknown) =>
      recordRef.update(data as any),
    setCollectionRecord: (model: Model, id: RecordId, data: unknown) => {
      const collection: RecordCollectionRef = docRef.getRecords(model);
      return collection.set(id, data as any);
    },
    deleteRecord: (recordRef: RecordRef) =>
      recordRef.delete(),
  } as VersionedDocRef;
}
