/* Generated by @palantir/pack.document-schema.type-gen@0.18.0 */

import type { DocumentRef, EditDescription, PresencePublishOptions, RecordId, RecordRef } from "@palantir/pack.document-schema.model-types";
import type { DocumentModel, NodeShapeModel, ShapeBoxModel, ShapeCircleModel, CanvasActivityModel, ShapeAddedActivityModel, ShapeDeletedActivityModel, ShapeUpdatedActivityModel, CursorPresenceModel, SelectionPresenceModel, FreehandStrokeModel } from "./models.js";
import type { CanvasActivity_v1, CursorPresence_v1, NodeShape_v1, SelectionPresence_v1, ShapeAddedActivity_v1, ShapeBox_v1, ShapeCircle_v1, ShapeDeletedActivity_v1, ShapeUpdatedActivity_v1 } from "./types_v1.js";
import type { CursorPresenceUpdate_v1, SelectionPresenceUpdate_v1, ShapeAddedActivityUpdate_v1, ShapeBoxUpdate_v1, ShapeCircleUpdate_v1, ShapeDeletedActivityUpdate_v1, ShapeUpdatedActivityUpdate_v1 } from "./writeTypes_v1.js";
import type { CanvasActivity_v2, CursorPresence_v2, NodeShape_v2, SelectionPresence_v2, ShapeAddedActivity_v2, ShapeBox_v2, ShapeCircle_v2, ShapeDeletedActivity_v2, ShapeUpdatedActivity_v2 } from "./types_v2.js";
import type { CursorPresenceUpdate_v2, SelectionPresenceUpdate_v2, ShapeAddedActivityUpdate_v2, ShapeBoxUpdate_v2, ShapeCircleUpdate_v2, ShapeDeletedActivityUpdate_v2, ShapeUpdatedActivityUpdate_v2 } from "./writeTypes_v2.js";
import type { CanvasActivity_v3, CursorPresence_v3, FreehandStroke_v3, NodeShape_v3, SelectionPresence_v3, ShapeAddedActivity_v3, ShapeBox_v3, ShapeCircle_v3, ShapeDeletedActivity_v3, ShapeUpdatedActivity_v3 } from "./types_v3.js";
import type { CursorPresenceUpdate_v3, FreehandStrokeUpdate_v3, SelectionPresenceUpdate_v3, ShapeAddedActivityUpdate_v3, ShapeBoxUpdate_v3, ShapeCircleUpdate_v3, ShapeDeletedActivityUpdate_v3, ShapeUpdatedActivityUpdate_v3 } from "./writeTypes_v3.js";

export interface VersionedDocRef_v1 extends DocumentRef<DocumentModel> {
  readonly version: 1;
  updateRecord(ref: RecordRef<typeof NodeShapeModel>, data: Partial<NodeShape_v1>): Promise<void>;
  updateRecord(ref: RecordRef<typeof ShapeBoxModel>, data: ShapeBoxUpdate_v1): Promise<void>;
  updateRecord(ref: RecordRef<typeof ShapeCircleModel>, data: ShapeCircleUpdate_v1): Promise<void>;
  updateRecord(ref: RecordRef<typeof CanvasActivityModel>, data: Partial<CanvasActivity_v1>): Promise<void>;
  updateRecord(ref: RecordRef<typeof ShapeAddedActivityModel>, data: ShapeAddedActivityUpdate_v1): Promise<void>;
  updateRecord(ref: RecordRef<typeof ShapeDeletedActivityModel>, data: ShapeDeletedActivityUpdate_v1): Promise<void>;
  updateRecord(ref: RecordRef<typeof ShapeUpdatedActivityModel>, data: ShapeUpdatedActivityUpdate_v1): Promise<void>;
  updateRecord(ref: RecordRef<typeof CursorPresenceModel>, data: CursorPresenceUpdate_v1): Promise<void>;
  updateRecord(ref: RecordRef<typeof SelectionPresenceModel>, data: SelectionPresenceUpdate_v1): Promise<void>;
  setRecord(model: typeof NodeShapeModel, id: RecordId, data: NodeShape_v1): Promise<void>;
  setRecord(model: typeof ShapeBoxModel, id: RecordId, data: ShapeBox_v1): Promise<void>;
  setRecord(model: typeof ShapeCircleModel, id: RecordId, data: ShapeCircle_v1): Promise<void>;
  setRecord(model: typeof CanvasActivityModel, id: RecordId, data: CanvasActivity_v1): Promise<void>;
  setRecord(model: typeof ShapeAddedActivityModel, id: RecordId, data: ShapeAddedActivity_v1): Promise<void>;
  setRecord(model: typeof ShapeDeletedActivityModel, id: RecordId, data: ShapeDeletedActivity_v1): Promise<void>;
  setRecord(model: typeof ShapeUpdatedActivityModel, id: RecordId, data: ShapeUpdatedActivity_v1): Promise<void>;
  setRecord(model: typeof CursorPresenceModel, id: RecordId, data: CursorPresence_v1): Promise<void>;
  setRecord(model: typeof SelectionPresenceModel, id: RecordId, data: SelectionPresence_v1): Promise<void>;
  updateCustomPresence(model: typeof NodeShapeModel, data: NodeShape_v1, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof ShapeBoxModel, data: ShapeBox_v1, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof ShapeCircleModel, data: ShapeCircle_v1, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof CanvasActivityModel, data: CanvasActivity_v1, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof ShapeAddedActivityModel, data: ShapeAddedActivity_v1, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof ShapeDeletedActivityModel, data: ShapeDeletedActivity_v1, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof ShapeUpdatedActivityModel, data: ShapeUpdatedActivity_v1, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof CursorPresenceModel, data: CursorPresence_v1, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof SelectionPresenceModel, data: SelectionPresence_v1, options?: PresencePublishOptions): void;
  describeEdit(model: typeof NodeShapeModel, data: NodeShape_v1): EditDescription<typeof NodeShapeModel>;
  describeEdit(model: typeof ShapeBoxModel, data: ShapeBox_v1): EditDescription<typeof ShapeBoxModel>;
  describeEdit(model: typeof ShapeCircleModel, data: ShapeCircle_v1): EditDescription<typeof ShapeCircleModel>;
  describeEdit(model: typeof CanvasActivityModel, data: CanvasActivity_v1): EditDescription<typeof CanvasActivityModel>;
  describeEdit(model: typeof ShapeAddedActivityModel, data: ShapeAddedActivity_v1): EditDescription<typeof ShapeAddedActivityModel>;
  describeEdit(model: typeof ShapeDeletedActivityModel, data: ShapeDeletedActivity_v1): EditDescription<typeof ShapeDeletedActivityModel>;
  describeEdit(model: typeof ShapeUpdatedActivityModel, data: ShapeUpdatedActivity_v1): EditDescription<typeof ShapeUpdatedActivityModel>;
  describeEdit(model: typeof CursorPresenceModel, data: CursorPresence_v1): EditDescription<typeof CursorPresenceModel>;
  describeEdit(model: typeof SelectionPresenceModel, data: SelectionPresence_v1): EditDescription<typeof SelectionPresenceModel>;
}

export interface VersionedDocRef_v2 extends DocumentRef<DocumentModel> {
  readonly version: 2;
  updateRecord(ref: RecordRef<typeof NodeShapeModel>, data: Partial<NodeShape_v2>): Promise<void>;
  updateRecord(ref: RecordRef<typeof ShapeBoxModel>, data: ShapeBoxUpdate_v2): Promise<void>;
  updateRecord(ref: RecordRef<typeof ShapeCircleModel>, data: ShapeCircleUpdate_v2): Promise<void>;
  updateRecord(ref: RecordRef<typeof CanvasActivityModel>, data: Partial<CanvasActivity_v2>): Promise<void>;
  updateRecord(ref: RecordRef<typeof ShapeAddedActivityModel>, data: ShapeAddedActivityUpdate_v2): Promise<void>;
  updateRecord(ref: RecordRef<typeof ShapeDeletedActivityModel>, data: ShapeDeletedActivityUpdate_v2): Promise<void>;
  updateRecord(ref: RecordRef<typeof ShapeUpdatedActivityModel>, data: ShapeUpdatedActivityUpdate_v2): Promise<void>;
  updateRecord(ref: RecordRef<typeof CursorPresenceModel>, data: CursorPresenceUpdate_v2): Promise<void>;
  updateRecord(ref: RecordRef<typeof SelectionPresenceModel>, data: SelectionPresenceUpdate_v2): Promise<void>;
  setRecord(model: typeof NodeShapeModel, id: RecordId, data: NodeShape_v2): Promise<void>;
  setRecord(model: typeof ShapeBoxModel, id: RecordId, data: ShapeBox_v2): Promise<void>;
  setRecord(model: typeof ShapeCircleModel, id: RecordId, data: ShapeCircle_v2): Promise<void>;
  setRecord(model: typeof CanvasActivityModel, id: RecordId, data: CanvasActivity_v2): Promise<void>;
  setRecord(model: typeof ShapeAddedActivityModel, id: RecordId, data: ShapeAddedActivity_v2): Promise<void>;
  setRecord(model: typeof ShapeDeletedActivityModel, id: RecordId, data: ShapeDeletedActivity_v2): Promise<void>;
  setRecord(model: typeof ShapeUpdatedActivityModel, id: RecordId, data: ShapeUpdatedActivity_v2): Promise<void>;
  setRecord(model: typeof CursorPresenceModel, id: RecordId, data: CursorPresence_v2): Promise<void>;
  setRecord(model: typeof SelectionPresenceModel, id: RecordId, data: SelectionPresence_v2): Promise<void>;
  updateCustomPresence(model: typeof NodeShapeModel, data: NodeShape_v2, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof ShapeBoxModel, data: ShapeBox_v2, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof ShapeCircleModel, data: ShapeCircle_v2, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof CanvasActivityModel, data: CanvasActivity_v2, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof ShapeAddedActivityModel, data: ShapeAddedActivity_v2, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof ShapeDeletedActivityModel, data: ShapeDeletedActivity_v2, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof ShapeUpdatedActivityModel, data: ShapeUpdatedActivity_v2, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof CursorPresenceModel, data: CursorPresence_v2, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof SelectionPresenceModel, data: SelectionPresence_v2, options?: PresencePublishOptions): void;
  describeEdit(model: typeof NodeShapeModel, data: NodeShape_v2): EditDescription<typeof NodeShapeModel>;
  describeEdit(model: typeof ShapeBoxModel, data: ShapeBox_v2): EditDescription<typeof ShapeBoxModel>;
  describeEdit(model: typeof ShapeCircleModel, data: ShapeCircle_v2): EditDescription<typeof ShapeCircleModel>;
  describeEdit(model: typeof CanvasActivityModel, data: CanvasActivity_v2): EditDescription<typeof CanvasActivityModel>;
  describeEdit(model: typeof ShapeAddedActivityModel, data: ShapeAddedActivity_v2): EditDescription<typeof ShapeAddedActivityModel>;
  describeEdit(model: typeof ShapeDeletedActivityModel, data: ShapeDeletedActivity_v2): EditDescription<typeof ShapeDeletedActivityModel>;
  describeEdit(model: typeof ShapeUpdatedActivityModel, data: ShapeUpdatedActivity_v2): EditDescription<typeof ShapeUpdatedActivityModel>;
  describeEdit(model: typeof CursorPresenceModel, data: CursorPresence_v2): EditDescription<typeof CursorPresenceModel>;
  describeEdit(model: typeof SelectionPresenceModel, data: SelectionPresence_v2): EditDescription<typeof SelectionPresenceModel>;
}

export interface VersionedDocRef_v3 extends DocumentRef<DocumentModel> {
  readonly version: 3;
  updateRecord(ref: RecordRef<typeof NodeShapeModel>, data: Partial<NodeShape_v3>): Promise<void>;
  updateRecord(ref: RecordRef<typeof ShapeBoxModel>, data: ShapeBoxUpdate_v3): Promise<void>;
  updateRecord(ref: RecordRef<typeof ShapeCircleModel>, data: ShapeCircleUpdate_v3): Promise<void>;
  updateRecord(ref: RecordRef<typeof CanvasActivityModel>, data: Partial<CanvasActivity_v3>): Promise<void>;
  updateRecord(ref: RecordRef<typeof ShapeAddedActivityModel>, data: ShapeAddedActivityUpdate_v3): Promise<void>;
  updateRecord(ref: RecordRef<typeof ShapeDeletedActivityModel>, data: ShapeDeletedActivityUpdate_v3): Promise<void>;
  updateRecord(ref: RecordRef<typeof ShapeUpdatedActivityModel>, data: ShapeUpdatedActivityUpdate_v3): Promise<void>;
  updateRecord(ref: RecordRef<typeof CursorPresenceModel>, data: CursorPresenceUpdate_v3): Promise<void>;
  updateRecord(ref: RecordRef<typeof SelectionPresenceModel>, data: SelectionPresenceUpdate_v3): Promise<void>;
  updateRecord(ref: RecordRef<typeof FreehandStrokeModel>, data: FreehandStrokeUpdate_v3): Promise<void>;
  setRecord(model: typeof NodeShapeModel, id: RecordId, data: NodeShape_v3): Promise<void>;
  setRecord(model: typeof ShapeBoxModel, id: RecordId, data: ShapeBox_v3): Promise<void>;
  setRecord(model: typeof ShapeCircleModel, id: RecordId, data: ShapeCircle_v3): Promise<void>;
  setRecord(model: typeof CanvasActivityModel, id: RecordId, data: CanvasActivity_v3): Promise<void>;
  setRecord(model: typeof ShapeAddedActivityModel, id: RecordId, data: ShapeAddedActivity_v3): Promise<void>;
  setRecord(model: typeof ShapeDeletedActivityModel, id: RecordId, data: ShapeDeletedActivity_v3): Promise<void>;
  setRecord(model: typeof ShapeUpdatedActivityModel, id: RecordId, data: ShapeUpdatedActivity_v3): Promise<void>;
  setRecord(model: typeof CursorPresenceModel, id: RecordId, data: CursorPresence_v3): Promise<void>;
  setRecord(model: typeof SelectionPresenceModel, id: RecordId, data: SelectionPresence_v3): Promise<void>;
  setRecord(model: typeof FreehandStrokeModel, id: RecordId, data: FreehandStroke_v3): Promise<void>;
  updateCustomPresence(model: typeof NodeShapeModel, data: NodeShape_v3, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof ShapeBoxModel, data: ShapeBox_v3, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof ShapeCircleModel, data: ShapeCircle_v3, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof CanvasActivityModel, data: CanvasActivity_v3, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof ShapeAddedActivityModel, data: ShapeAddedActivity_v3, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof ShapeDeletedActivityModel, data: ShapeDeletedActivity_v3, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof ShapeUpdatedActivityModel, data: ShapeUpdatedActivity_v3, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof CursorPresenceModel, data: CursorPresence_v3, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof SelectionPresenceModel, data: SelectionPresence_v3, options?: PresencePublishOptions): void;
  updateCustomPresence(model: typeof FreehandStrokeModel, data: FreehandStroke_v3, options?: PresencePublishOptions): void;
  describeEdit(model: typeof NodeShapeModel, data: NodeShape_v3): EditDescription<typeof NodeShapeModel>;
  describeEdit(model: typeof ShapeBoxModel, data: ShapeBox_v3): EditDescription<typeof ShapeBoxModel>;
  describeEdit(model: typeof ShapeCircleModel, data: ShapeCircle_v3): EditDescription<typeof ShapeCircleModel>;
  describeEdit(model: typeof CanvasActivityModel, data: CanvasActivity_v3): EditDescription<typeof CanvasActivityModel>;
  describeEdit(model: typeof ShapeAddedActivityModel, data: ShapeAddedActivity_v3): EditDescription<typeof ShapeAddedActivityModel>;
  describeEdit(model: typeof ShapeDeletedActivityModel, data: ShapeDeletedActivity_v3): EditDescription<typeof ShapeDeletedActivityModel>;
  describeEdit(model: typeof ShapeUpdatedActivityModel, data: ShapeUpdatedActivity_v3): EditDescription<typeof ShapeUpdatedActivityModel>;
  describeEdit(model: typeof CursorPresenceModel, data: CursorPresence_v3): EditDescription<typeof CursorPresenceModel>;
  describeEdit(model: typeof SelectionPresenceModel, data: SelectionPresence_v3): EditDescription<typeof SelectionPresenceModel>;
  describeEdit(model: typeof FreehandStrokeModel, data: FreehandStroke_v3): EditDescription<typeof FreehandStrokeModel>;
}

export type VersionedDocRef = VersionedDocRef_v1 | VersionedDocRef_v2 | VersionedDocRef_v3;

/** Narrow a DocumentRef to a version-discriminated type for type-safe writes. */
export function asVersioned(docRef: DocumentRef<DocumentModel>): VersionedDocRef {
  return docRef as VersionedDocRef;
}

/**
 * Exhaustive version handler. TypeScript enforces that every supported
 * version has a corresponding handler -- adding a new schema version
 * produces a compile error at every call site until handled.
 */
export function matchVersion<R>(
  doc: VersionedDocRef,
  handlers: {
  readonly 1: (doc: VersionedDocRef_v1) => R;
  readonly 2: (doc: VersionedDocRef_v2) => R;
  readonly 3: (doc: VersionedDocRef_v3) => R;
  },
): R {
  switch (doc.version) {
    case 1:
      return handlers[1](doc);
    case 2:
      return handlers[2](doc);
    case 3:
      return handlers[3](doc);
    default:
      throw new Error(`Unexpected document version: ${(doc as any).version}`);
  }
}
