/* Generated by @palantir/pack.document-schema.type-gen@0.5.0 */

import type { DocumentRef, Model, ModelData, RecordId, RecordRef } from "@palantir/pack.document-schema.model-types";
import type { DocumentModel, ActivityEventModel, ActivityShapeAddEventModel, ActivityShapeDeleteEventModel, ActivityShapeUpdateEventModel, NodeShapeModel, PresenceCursorEventModel, PresenceEventModel, PresenceSelectionEventModel, ShapeBoxModel, ShapeCircleModel } from "./models.js";
import type { ActivityEvent_v2, ActivityShapeAddEvent_v2, ActivityShapeDeleteEvent_v2, ActivityShapeUpdateEvent_v2, NodeShape_v2, PresenceCursorEvent_v2, PresenceEvent_v2, PresenceSelectionEvent_v2, ShapeBox_v2, ShapeCircle_v2 } from "./types_v2.js";
import type { ActivityShapeAddEventUpdate_v2, ActivityShapeDeleteEventUpdate_v2, ActivityShapeUpdateEventUpdate_v2, PresenceCursorEventUpdate_v2, PresenceSelectionEventUpdate_v2, ShapeBoxUpdate_v2, ShapeCircleUpdate_v2 } from "./writeTypes_v2.js";

export interface VersionedDocRef_v2 extends DocumentRef<DocumentModel> {
  readonly version: 2;
  updateRecord(ref: RecordRef<typeof NodeShapeModel>, data: Partial<NodeShape_v2>): Promise<void>;
  updateRecord(ref: RecordRef<typeof ShapeBoxModel>, data: ShapeBoxUpdate_v2): Promise<void>;
  updateRecord(ref: RecordRef<typeof ShapeCircleModel>, data: ShapeCircleUpdate_v2): Promise<void>;
  updateRecord<M extends Model>(ref: RecordRef<M>, data: Partial<ModelData<M>>): Promise<void>;
  setCollectionRecord(model: typeof NodeShapeModel, id: RecordId, data: NodeShape_v2): Promise<void>;
  setCollectionRecord(model: typeof ShapeBoxModel, id: RecordId, data: ShapeBox_v2): Promise<void>;
  setCollectionRecord(model: typeof ShapeCircleModel, id: RecordId, data: ShapeCircle_v2): Promise<void>;
  setCollectionRecord<M extends Model>(model: M, id: RecordId, data: ModelData<M>): Promise<void>;
}

export type VersionedDocRef = VersionedDocRef_v2;

/** Narrow a DocumentRef to a version-discriminated type for type-safe writes. */
export function asVersioned(docRef: DocumentRef<DocumentModel>): VersionedDocRef {
  return docRef as VersionedDocRef;
}
