/* Generated by @palantir/pack.document-schema.type-gen@0.12.0 */

import type { NodeShape_v3 } from "./types_v3.js";

export type ShapeBoxUpdate_v3 = {
  readonly bottom?: number;
  readonly left?: number;
  readonly right?: number;
  readonly top?: number;
  readonly fillColor?: string;
  readonly strokeColor?: string;
  readonly opacity?: number;
};

export type ShapeCircleUpdate_v3 = {
  readonly bottom?: number;
  readonly left?: number;
  readonly right?: number;
  readonly top?: number;
  readonly fillColor?: string;
  readonly strokeColor?: string;
  readonly opacity?: number;
};

export type ShapeAddedActivityUpdate_v3 = {
  readonly nodeId?: string;
};

export type ShapeDeletedActivityUpdate_v3 = {
  readonly nodeId?: string;
};

export type ShapeUpdatedActivityUpdate_v3 = {
  readonly nodeId?: string;
  readonly oldShape?: NodeShape_v3;
  readonly newShape?: NodeShape_v3;
};

export type CursorPresenceUpdate_v3 = {
  readonly x?: number;
  readonly y?: number;
};

export type SelectionPresenceUpdate_v3 = {
  readonly selectedNodeIds?: readonly string[];
};

export type FreehandStrokeUpdate_v3 = {
  readonly points?: string;
  readonly color?: string;
};

