/* Generated by @palantir/pack.document-schema.type-gen@0.17.0 */

import type { NodeShape_v1 } from "./types_v1.js";

export type ShapeBoxUpdate_v1 = {
  readonly bottom?: number;
  readonly left?: number;
  readonly right?: number;
  readonly top?: number;
  readonly color?: string;
};

export type ShapeCircleUpdate_v1 = {
  readonly bottom?: number;
  readonly left?: number;
  readonly right?: number;
  readonly top?: number;
  readonly color?: string;
};

export type ShapeAddedActivityUpdate_v1 = {
  readonly nodeId?: string;
};

export type ShapeDeletedActivityUpdate_v1 = {
  readonly nodeId?: string;
};

export type ShapeUpdatedActivityUpdate_v1 = {
  readonly nodeId?: string;
  readonly oldShape?: NodeShape_v1;
  readonly newShape?: NodeShape_v1;
};

export type CursorPresenceUpdate_v1 = {
  readonly x?: number;
  readonly y?: number;
};

export type SelectionPresenceUpdate_v1 = {
  readonly selectedNodeIds?: readonly string[];
};

