/* Generated by @palantir/pack.document-schema.type-gen@0.13.0 */

import type { NodeShape_v2 } from "./types_v2.js";

export type ShapeBoxUpdate_v2 = {
  readonly bottom?: number;
  readonly left?: number;
  readonly right?: number;
  readonly top?: number;
  readonly fillColor?: string;
  readonly strokeColor?: string;
  readonly opacity?: number;
};

export type ShapeCircleUpdate_v2 = {
  readonly bottom?: number;
  readonly left?: number;
  readonly right?: number;
  readonly top?: number;
  readonly fillColor?: string;
  readonly strokeColor?: string;
  readonly opacity?: number;
};

export type ShapeAddedActivityUpdate_v2 = {
  readonly nodeId?: string;
};

export type ShapeDeletedActivityUpdate_v2 = {
  readonly nodeId?: string;
};

export type ShapeUpdatedActivityUpdate_v2 = {
  readonly nodeId?: string;
  readonly oldShape?: NodeShape_v2;
  readonly newShape?: NodeShape_v2;
};

export type CursorPresenceUpdate_v2 = {
  readonly x?: number;
  readonly y?: number;
};

export type SelectionPresenceUpdate_v2 = {
  readonly selectedNodeIds?: readonly string[];
};

