/* Generated by @palantir/pack.document-schema.type-gen@0.5.0 */

import type { NodeShape_v2 } from "./types_v2.js";

export type ActivityShapeAddEventUpdate_v2 = {
  readonly nodeId?: string;
};

export type ActivityShapeDeleteEventUpdate_v2 = {
  readonly nodeId?: string;
};

export type ActivityShapeUpdateEventUpdate_v2 = {
  readonly nodeId?: string;
  readonly oldShape?: NodeShape_v2;
  readonly newShape?: NodeShape_v2;
};

export type PresenceCursorEventUpdate_v2 = {
  readonly x?: number;
  readonly y?: number;
};

export type PresenceSelectionEventUpdate_v2 = {
  readonly selectedNodeIds?: readonly string[];
};

export type ShapeBoxUpdate_v2 = {
  readonly bottom?: number;
  readonly left?: number;
  readonly right?: number;
  readonly top?: number;
  readonly fillColor?: string;
  readonly strokeColor?: string;
  readonly opacity?: number;
};

export type ShapeCircleUpdate_v2 = {
  readonly bottom?: number;
  readonly left?: number;
  readonly right?: number;
  readonly top?: number;
  readonly fillColor?: string;
  readonly strokeColor?: string;
  readonly opacity?: number;
};

