/* Generated by @palantir/pack.document-schema.type-gen@0.9.0 */

import type { NodeShape_v1 } from "./types_v1.js";

export type ActivityShapeAddEventUpdate_v1 = {
  readonly nodeId?: string;
};

export type ActivityShapeDeleteEventUpdate_v1 = {
  readonly nodeId?: string;
};

export type ActivityShapeUpdateEventUpdate_v1 = {
  readonly nodeId?: string;
  readonly oldShape?: NodeShape_v1;
  readonly newShape?: NodeShape_v1;
};

export type PresenceCursorEventUpdate_v1 = {
  readonly x?: number;
  readonly y?: number;
};

export type PresenceSelectionEventUpdate_v1 = {
  readonly selectedNodeIds?: readonly string[];
};

export type ShapeBoxUpdate_v1 = {
  readonly bottom?: number;
  readonly left?: number;
  readonly right?: number;
  readonly top?: number;
  readonly color?: string;
};

export type ShapeCircleUpdate_v1 = {
  readonly bottom?: number;
  readonly left?: number;
  readonly right?: number;
  readonly top?: number;
  readonly color?: string;
};

