/*
 * Copyright 2025 Palantir Technologies, Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// The hand-written docs are autogenerated from the filesystem (ordered by each
// page's `sidebar_position`), so adding or removing a page needs no edit here.
// The API Reference is generated by docusaurus-plugin-typedoc.
const sidebars: SidebarsConfig = {
  docs: [
    "intro",
    {
      type: "category",
      label: "Getting Started",
      link: { type: "generated-index", slug: "/getting-started" },
      items: [{ type: "autogenerated", dirName: "getting-started" }],
    },
    {
      type: "category",
      label: "Guides",
      link: { type: "generated-index", slug: "/guides" },
      items: [{ type: "autogenerated", dirName: "guides" }],
    },
    {
      type: "category",
      label: "API Reference",
      items: [
        {
          type: "category",
          label: "@palantir/pack.schema",
          link: { type: "doc", id: "api/schema/index" },
          items: require("./api/schema/typedoc-sidebar.cjs"),
        },
      ],
    },
  ],
};

export default sidebars;
