/* Generated by @palantir/pack.document-schema.type-gen@0.5.0 */

import type { MigrationRegistry } from "@palantir/pack.document-schema.model-types";

export const ActivityShapeAddEventMigrations: MigrationRegistry<"ActivityShapeAddEvent"> = {
  modelName: "ActivityShapeAddEvent",
  allFields: {
    nodeId: { type: { kind: "primitive" } },
  },
  steps: [
  ],
};

export const ActivityShapeDeleteEventMigrations: MigrationRegistry<"ActivityShapeDeleteEvent"> = {
  modelName: "ActivityShapeDeleteEvent",
  allFields: {
    nodeId: { type: { kind: "primitive" } },
  },
  steps: [
  ],
};

export const ActivityShapeUpdateEventMigrations: MigrationRegistry<"ActivityShapeUpdateEvent"> = {
  modelName: "ActivityShapeUpdateEvent",
  allFields: {
    newShape: { type: { kind: "modelRef", model: "NodeShape" } },
    nodeId: { type: { kind: "primitive" } },
    oldShape: { type: { kind: "modelRef", model: "NodeShape" } },
  },
  steps: [
  ],
};

export const PresenceCursorEventMigrations: MigrationRegistry<"PresenceCursorEvent"> = {
  modelName: "PresenceCursorEvent",
  allFields: {
    x: { type: { kind: "primitive" } },
    y: { type: { kind: "primitive" } },
  },
  steps: [
  ],
};

export const PresenceSelectionEventMigrations: MigrationRegistry<"PresenceSelectionEvent"> = {
  modelName: "PresenceSelectionEvent",
  allFields: {
    selectedNodeIds: { type: { kind: "array", element: { kind: "primitive" } } },
  },
  steps: [
  ],
};

export const ShapeBoxMigrations: MigrationRegistry<"ShapeBox"> = {
  modelName: "ShapeBox",
  allFields: {
    bottom: { type: { kind: "primitive" } },
    color: { type: { kind: "optional", inner: { kind: "primitive" } } },
    fillColor: { type: { kind: "optional", inner: { kind: "primitive" } } },
    left: { type: { kind: "primitive" } },
    opacity: { type: { kind: "optional", inner: { kind: "primitive" } }, default: 1 },
    right: { type: { kind: "primitive" } },
    strokeColor: { type: { kind: "optional", inner: { kind: "primitive" } } },
    top: { type: { kind: "primitive" } },
  },
  steps: [
    {
      name: "v2",
      addedInVersion: 2,
      fields: {
        fillColor: {
          derivedFrom: ["color"],
          forward: ({ color }) => color,
        },
        strokeColor: {
          derivedFrom: ["color"],
          forward: ({ color }) => color,
        },
        opacity: {
          derivedFrom: [],
          forward: () => undefined,
          default: 1,
        },
      },
      removedFields: ["color"],
    },
  ],
};

export const ShapeCircleMigrations: MigrationRegistry<"ShapeCircle"> = {
  modelName: "ShapeCircle",
  allFields: {
    bottom: { type: { kind: "primitive" } },
    color: { type: { kind: "optional", inner: { kind: "primitive" } } },
    fillColor: { type: { kind: "optional", inner: { kind: "primitive" } } },
    left: { type: { kind: "primitive" } },
    opacity: { type: { kind: "optional", inner: { kind: "primitive" } }, default: 1 },
    right: { type: { kind: "primitive" } },
    strokeColor: { type: { kind: "optional", inner: { kind: "primitive" } } },
    top: { type: { kind: "primitive" } },
  },
  steps: [
    {
      name: "v2",
      addedInVersion: 2,
      fields: {
        fillColor: {
          derivedFrom: ["color"],
          forward: ({ color }) => color,
        },
        strokeColor: {
          derivedFrom: ["color"],
          forward: ({ color }) => color,
        },
        opacity: {
          derivedFrom: [],
          forward: () => undefined,
          default: 1,
        },
      },
      removedFields: ["color"],
    },
  ],
};

