/* Generated by @palantir/pack.document-schema.type-gen@0.9.0 */

import { z } from "zod";

export const ActivityShapeAddEventInternalSchema = z.object({
  nodeId: z.string(),
}).passthrough();

export const ActivityShapeDeleteEventInternalSchema = z.object({
  nodeId: z.string(),
}).passthrough();

export const ActivityShapeUpdateEventInternalSchema = z.object({
  newShape: z.unknown(),
  nodeId: z.string(),
  oldShape: z.unknown(),
}).passthrough();

export const FreehandStrokeInternalSchema = z.object({
  color: z.string().optional(),
  points: z.string().optional(),
}).passthrough();

export const PresenceCursorEventInternalSchema = z.object({
  x: z.number(),
  y: z.number(),
}).passthrough();

export const PresenceSelectionEventInternalSchema = z.object({
  selectedNodeIds: z.array(z.string()),
}).passthrough();

export const ShapeBoxInternalSchema = z.object({
  bottom: z.number(),
  color: z.string().optional(),
  fillColor: z.string().optional(),
  left: z.number(),
  opacity: z.number().optional(),
  right: z.number(),
  strokeColor: z.string().optional(),
  top: z.number(),
}).passthrough();

export const ShapeCircleInternalSchema = z.object({
  bottom: z.number(),
  color: z.string().optional(),
  fillColor: z.string().optional(),
  left: z.number(),
  opacity: z.number().optional(),
  right: z.number(),
  strokeColor: z.string().optional(),
  top: z.number(),
}).passthrough();

