/* Generated by @palantir/pack.document-schema.type-gen@0.12.0 */

import { z } from "zod";

export const CursorPresenceInternalSchema = z.object({
  x: z.number(),
  y: z.number(),
}).passthrough();

export const FreehandStrokeInternalSchema = z.object({
  color: z.string().optional(),
  points: z.string().optional(),
}).passthrough();

export const SelectionPresenceInternalSchema = z.object({
  selectedNodeIds: z.array(z.string()),
}).passthrough();

export const ShapeAddedActivityInternalSchema = z.object({
  nodeId: z.string(),
}).passthrough();

export const ShapeBoxInternalSchema = z.object({
  bottom: z.number(),
  color: z.string().optional(),
  fillColor: z.string().optional(),
  left: z.number(),
  opacity: z.number().optional(),
  right: z.number(),
  strokeColor: z.string().optional(),
  top: z.number(),
}).passthrough();

export const ShapeCircleInternalSchema = z.object({
  bottom: z.number(),
  color: z.string().optional(),
  fillColor: z.string().optional(),
  left: z.number(),
  opacity: z.number().optional(),
  right: z.number(),
  strokeColor: z.string().optional(),
  top: z.number(),
}).passthrough();

export const ShapeDeletedActivityInternalSchema = z.object({
  nodeId: z.string(),
}).passthrough();

export const ShapeUpdatedActivityInternalSchema = z.object({
  newShape: z.unknown(),
  nodeId: z.string(),
  oldShape: z.unknown(),
}).passthrough();

