/* Generated by @palantir/pack.document-schema.type-gen@0.12.0 */


/** Internal representation containing all fields across all schema versions. */
export interface CursorPresence__Internal {
  readonly x: number;
  readonly y: number;
}

/** Internal representation containing all fields across all schema versions. */
export interface FreehandStroke__Internal {
  readonly color?: (string | undefined);
  readonly points?: string;
}

/** Internal representation containing all fields across all schema versions. */
export interface SelectionPresence__Internal {
  readonly selectedNodeIds: readonly string[];
}

/** Internal representation containing all fields across all schema versions. */
export interface ShapeAddedActivity__Internal {
  readonly nodeId: string;
}

/** Internal representation containing all fields across all schema versions. */
export interface ShapeBox__Internal {
  readonly bottom: number;
  readonly color?: (string | undefined);
  readonly fillColor?: (string | undefined);
  readonly left: number;
  readonly opacity?: (number | undefined);
  readonly right: number;
  readonly strokeColor?: (string | undefined);
  readonly top: number;
}

/** Internal representation containing all fields across all schema versions. */
export interface ShapeCircle__Internal {
  readonly bottom: number;
  readonly color?: (string | undefined);
  readonly fillColor?: (string | undefined);
  readonly left: number;
  readonly opacity?: (number | undefined);
  readonly right: number;
  readonly strokeColor?: (string | undefined);
  readonly top: number;
}

/** Internal representation containing all fields across all schema versions. */
export interface ShapeDeletedActivity__Internal {
  readonly nodeId: string;
}

/** Internal representation containing all fields across all schema versions. */
export interface ShapeUpdatedActivity__Internal {
  readonly newShape: unknown;
  readonly nodeId: string;
  readonly oldShape: unknown;
}

/** Internal representation of CursorPresence at schema version 1. */
export interface CursorPresence__v1 {
  readonly x: number;
  readonly y: number;
}

/** Internal representation of CursorPresence at schema version 2. */
export interface CursorPresence__v2 {
  readonly x: number;
  readonly y: number;
}

/** Internal representation of CursorPresence at schema version 3. */
export interface CursorPresence__v3 {
  readonly x: number;
  readonly y: number;
}

/** Internal representation of FreehandStroke at schema version 3. */
export interface FreehandStroke__v3 {
  readonly color?: (string | undefined);
  readonly points: string;
}

/** Internal representation of SelectionPresence at schema version 1. */
export interface SelectionPresence__v1 {
  readonly selectedNodeIds: readonly string[];
}

/** Internal representation of SelectionPresence at schema version 2. */
export interface SelectionPresence__v2 {
  readonly selectedNodeIds: readonly string[];
}

/** Internal representation of SelectionPresence at schema version 3. */
export interface SelectionPresence__v3 {
  readonly selectedNodeIds: readonly string[];
}

/** Internal representation of ShapeAddedActivity at schema version 1. */
export interface ShapeAddedActivity__v1 {
  readonly nodeId: string;
}

/** Internal representation of ShapeAddedActivity at schema version 2. */
export interface ShapeAddedActivity__v2 {
  readonly nodeId: string;
}

/** Internal representation of ShapeAddedActivity at schema version 3. */
export interface ShapeAddedActivity__v3 {
  readonly nodeId: string;
}

/** Internal representation of ShapeBox at schema version 1. */
export interface ShapeBox__v1 {
  readonly bottom: number;
  readonly color?: (string | undefined);
  readonly left: number;
  readonly right: number;
  readonly top: number;
}

/** Internal representation of ShapeBox at schema version 2. */
export interface ShapeBox__v2 {
  readonly bottom: number;
  readonly fillColor?: (string | undefined);
  readonly left: number;
  readonly opacity?: (number | undefined);
  readonly right: number;
  readonly strokeColor?: (string | undefined);
  readonly top: number;
}

/** Internal representation of ShapeBox at schema version 3. */
export interface ShapeBox__v3 {
  readonly bottom: number;
  readonly fillColor?: (string | undefined);
  readonly left: number;
  readonly opacity?: (number | undefined);
  readonly right: number;
  readonly strokeColor?: (string | undefined);
  readonly top: number;
}

/** Internal representation of ShapeCircle at schema version 1. */
export interface ShapeCircle__v1 {
  readonly bottom: number;
  readonly color?: (string | undefined);
  readonly left: number;
  readonly right: number;
  readonly top: number;
}

/** Internal representation of ShapeCircle at schema version 2. */
export interface ShapeCircle__v2 {
  readonly bottom: number;
  readonly fillColor?: (string | undefined);
  readonly left: number;
  readonly opacity?: (number | undefined);
  readonly right: number;
  readonly strokeColor?: (string | undefined);
  readonly top: number;
}

/** Internal representation of ShapeCircle at schema version 3. */
export interface ShapeCircle__v3 {
  readonly bottom: number;
  readonly fillColor?: (string | undefined);
  readonly left: number;
  readonly opacity?: (number | undefined);
  readonly right: number;
  readonly strokeColor?: (string | undefined);
  readonly top: number;
}

/** Internal representation of ShapeDeletedActivity at schema version 1. */
export interface ShapeDeletedActivity__v1 {
  readonly nodeId: string;
}

/** Internal representation of ShapeDeletedActivity at schema version 2. */
export interface ShapeDeletedActivity__v2 {
  readonly nodeId: string;
}

/** Internal representation of ShapeDeletedActivity at schema version 3. */
export interface ShapeDeletedActivity__v3 {
  readonly nodeId: string;
}

/** Internal representation of ShapeUpdatedActivity at schema version 1. */
export interface ShapeUpdatedActivity__v1 {
  readonly newShape: unknown;
  readonly nodeId: string;
  readonly oldShape: unknown;
}

/** Internal representation of ShapeUpdatedActivity at schema version 2. */
export interface ShapeUpdatedActivity__v2 {
  readonly newShape: unknown;
  readonly nodeId: string;
  readonly oldShape: unknown;
}

/** Internal representation of ShapeUpdatedActivity at schema version 3. */
export interface ShapeUpdatedActivity__v3 {
  readonly newShape: unknown;
  readonly nodeId: string;
  readonly oldShape: unknown;
}

