/* Generated by @palantir/pack.document-schema.type-gen@0.9.0 */


/** Internal representation containing all fields across all schema versions. */
export interface ActivityShapeAddEvent__Internal {
  readonly nodeId: string;
}

/** Internal representation containing all fields across all schema versions. */
export interface ActivityShapeDeleteEvent__Internal {
  readonly nodeId: string;
}

/** Internal representation containing all fields across all schema versions. */
export interface ActivityShapeUpdateEvent__Internal {
  readonly newShape: unknown;
  readonly nodeId: string;
  readonly oldShape: unknown;
}

/** Internal representation containing all fields across all schema versions. */
export interface FreehandStroke__Internal {
  readonly color?: (string | undefined);
  readonly points?: string;
}

/** Internal representation containing all fields across all schema versions. */
export interface PresenceCursorEvent__Internal {
  readonly x: number;
  readonly y: number;
}

/** Internal representation containing all fields across all schema versions. */
export interface PresenceSelectionEvent__Internal {
  readonly selectedNodeIds: readonly string[];
}

/** Internal representation containing all fields across all schema versions. */
export interface ShapeBox__Internal {
  readonly bottom: number;
  readonly color?: (string | undefined);
  readonly fillColor?: (string | undefined);
  readonly left: number;
  readonly opacity?: (number | undefined);
  readonly right: number;
  readonly strokeColor?: (string | undefined);
  readonly top: number;
}

/** Internal representation containing all fields across all schema versions. */
export interface ShapeCircle__Internal {
  readonly bottom: number;
  readonly color?: (string | undefined);
  readonly fillColor?: (string | undefined);
  readonly left: number;
  readonly opacity?: (number | undefined);
  readonly right: number;
  readonly strokeColor?: (string | undefined);
  readonly top: number;
}

