/* Generated by @palantir/pack.document-schema.type-gen@0.9.0 */

import type { UpgradeRegistry, UnionUpgradeRegistry } from "@palantir/pack.document-schema.model-types";

export const ActivityShapeAddEventUpgrades: UpgradeRegistry<"ActivityShapeAddEvent"> = {
  modelName: "ActivityShapeAddEvent",
  allFields: {
    nodeId: { type: { kind: "primitive" } },
  },
  steps: [
  ],
};

export const ActivityShapeDeleteEventUpgrades: UpgradeRegistry<"ActivityShapeDeleteEvent"> = {
  modelName: "ActivityShapeDeleteEvent",
  allFields: {
    nodeId: { type: { kind: "primitive" } },
  },
  steps: [
  ],
};

export const ActivityShapeUpdateEventUpgrades: UpgradeRegistry<"ActivityShapeUpdateEvent"> = {
  modelName: "ActivityShapeUpdateEvent",
  allFields: {
    newShape: { type: { kind: "modelRef", model: "NodeShape" } },
    nodeId: { type: { kind: "primitive" } },
    oldShape: { type: { kind: "modelRef", model: "NodeShape" } },
  },
  steps: [
  ],
};

export const FreehandStrokeUpgrades: UpgradeRegistry<"FreehandStroke"> = {
  modelName: "FreehandStroke",
  allFields: {
    color: { type: { kind: "optional", inner: { kind: "primitive" } } },
    points: { type: { kind: "primitive" } },
  },
  steps: [
  ],
};

export const PresenceCursorEventUpgrades: UpgradeRegistry<"PresenceCursorEvent"> = {
  modelName: "PresenceCursorEvent",
  allFields: {
    x: { type: { kind: "primitive" } },
    y: { type: { kind: "primitive" } },
  },
  steps: [
  ],
};

export const PresenceSelectionEventUpgrades: UpgradeRegistry<"PresenceSelectionEvent"> = {
  modelName: "PresenceSelectionEvent",
  allFields: {
    selectedNodeIds: { type: { kind: "array", element: { kind: "primitive" } } },
  },
  steps: [
  ],
};

export const ShapeBoxUpgrades: UpgradeRegistry<"ShapeBox"> = {
  modelName: "ShapeBox",
  allFields: {
    bottom: { type: { kind: "primitive" } },
    color: { type: { kind: "optional", inner: { kind: "primitive" } } },
    fillColor: { type: { kind: "optional", inner: { kind: "primitive" } } },
    left: { type: { kind: "primitive" } },
    opacity: { type: { kind: "optional", inner: { kind: "primitive" } } },
    right: { type: { kind: "primitive" } },
    strokeColor: { type: { kind: "optional", inner: { kind: "primitive" } } },
    top: { type: { kind: "primitive" } },
  },
  steps: [
    {
      name: "v2",
      addedInVersion: 2,
      fields: {
        fillColor: {
          derivedFrom: ["color"],
          forward: ({ color }) => color,
        },
        strokeColor: {
          derivedFrom: ["color"],
          forward: ({ color }) => color,
        },
        opacity: {
          derivedFrom: [],
          forward: () => undefined,
        },
      },
      removedFields: ["color"],
    },
  ],
};

export const ShapeCircleUpgrades: UpgradeRegistry<"ShapeCircle"> = {
  modelName: "ShapeCircle",
  allFields: {
    bottom: { type: { kind: "primitive" } },
    color: { type: { kind: "optional", inner: { kind: "primitive" } } },
    fillColor: { type: { kind: "optional", inner: { kind: "primitive" } } },
    left: { type: { kind: "primitive" } },
    opacity: { type: { kind: "optional", inner: { kind: "primitive" } } },
    right: { type: { kind: "primitive" } },
    strokeColor: { type: { kind: "optional", inner: { kind: "primitive" } } },
    top: { type: { kind: "primitive" } },
  },
  steps: [
    {
      name: "v2",
      addedInVersion: 2,
      fields: {
        fillColor: {
          derivedFrom: ["color"],
          forward: ({ color }) => color,
        },
        strokeColor: {
          derivedFrom: ["color"],
          forward: ({ color }) => color,
        },
        opacity: {
          derivedFrom: [],
          forward: () => undefined,
        },
      },
      removedFields: ["color"],
    },
  ],
};

export const ActivityEventUpgrades: UnionUpgradeRegistry<"ActivityEvent"> = {
  modelName: "ActivityEvent",
  discriminant: "eventType",
  variants: {
    "shapeAdd": "ActivityShapeAddEvent",
    "shapeDelete": "ActivityShapeDeleteEvent",
    "shapeUpdate": "ActivityShapeUpdateEvent",
  },
};

export const NodeShapeUpgrades: UnionUpgradeRegistry<"NodeShape"> = {
  modelName: "NodeShape",
  discriminant: "shapeType",
  variants: {
    "box": "ShapeBox",
    "circle": "ShapeCircle",
  },
};

export const PresenceEventUpgrades: UnionUpgradeRegistry<"PresenceEvent"> = {
  modelName: "PresenceEvent",
  discriminant: "eventType",
  variants: {
    "cursor": "PresenceCursorEvent",
    "selection": "PresenceSelectionEvent",
  },
};

