/* Generated by @palantir/pack.document-schema.type-gen@0.13.0 */

import type { UpgradeRegistry, UnionUpgradeRegistry } from "@palantir/pack.document-schema.model-types";

export const CursorPresenceUpgrades: UpgradeRegistry<"CursorPresence"> = {
  modelName: "CursorPresence",
  allFields: {
    x: { type: { kind: "primitive" } },
    y: { type: { kind: "primitive" } },
  },
  steps: [
  ],
};

export const FreehandStrokeUpgrades: UpgradeRegistry<"FreehandStroke"> = {
  modelName: "FreehandStroke",
  allFields: {
    color: { type: { kind: "optional", inner: { kind: "primitive" } } },
    points: { type: { kind: "primitive" } },
  },
  steps: [
  ],
};

export const SelectionPresenceUpgrades: UpgradeRegistry<"SelectionPresence"> = {
  modelName: "SelectionPresence",
  allFields: {
    selectedNodeIds: { type: { kind: "array", element: { kind: "primitive" } } },
  },
  steps: [
  ],
};

export const ShapeAddedActivityUpgrades: UpgradeRegistry<"ShapeAddedActivity"> = {
  modelName: "ShapeAddedActivity",
  allFields: {
    nodeId: { type: { kind: "primitive" } },
  },
  steps: [
  ],
};

export const ShapeBoxUpgrades: UpgradeRegistry<"ShapeBox"> = {
  modelName: "ShapeBox",
  allFields: {
    bottom: { type: { kind: "primitive" } },
    color: { type: { kind: "optional", inner: { kind: "primitive" } } },
    fillColor: { type: { kind: "optional", inner: { kind: "primitive" } } },
    left: { type: { kind: "primitive" } },
    opacity: { type: { kind: "optional", inner: { kind: "primitive" } } },
    right: { type: { kind: "primitive" } },
    strokeColor: { type: { kind: "optional", inner: { kind: "primitive" } } },
    top: { type: { kind: "primitive" } },
  },
  steps: [
    {
      addedInVersion: 2,
      fields: {
        fillColor: {
          derivedFrom: ["color"],
        },
        strokeColor: {
          derivedFrom: ["color"],
        },
        opacity: {
          derivedFrom: [],
        },
      },
      removedFields: ["color"],
    },
  ],
};

export const ShapeCircleUpgrades: UpgradeRegistry<"ShapeCircle"> = {
  modelName: "ShapeCircle",
  allFields: {
    bottom: { type: { kind: "primitive" } },
    color: { type: { kind: "optional", inner: { kind: "primitive" } } },
    fillColor: { type: { kind: "optional", inner: { kind: "primitive" } } },
    left: { type: { kind: "primitive" } },
    opacity: { type: { kind: "optional", inner: { kind: "primitive" } } },
    right: { type: { kind: "primitive" } },
    strokeColor: { type: { kind: "optional", inner: { kind: "primitive" } } },
    top: { type: { kind: "primitive" } },
  },
  steps: [
    {
      addedInVersion: 2,
      fields: {
        fillColor: {
          derivedFrom: ["color"],
        },
        strokeColor: {
          derivedFrom: ["color"],
        },
        opacity: {
          derivedFrom: [],
        },
      },
      removedFields: ["color"],
    },
  ],
};

export const ShapeDeletedActivityUpgrades: UpgradeRegistry<"ShapeDeletedActivity"> = {
  modelName: "ShapeDeletedActivity",
  allFields: {
    nodeId: { type: { kind: "primitive" } },
  },
  steps: [
  ],
};

export const ShapeUpdatedActivityUpgrades: UpgradeRegistry<"ShapeUpdatedActivity"> = {
  modelName: "ShapeUpdatedActivity",
  allFields: {
    newShape: { type: { kind: "modelRef", model: "NodeShape" } },
    nodeId: { type: { kind: "primitive" } },
    oldShape: { type: { kind: "modelRef", model: "NodeShape" } },
  },
  steps: [
  ],
};

export const NodeShapeUpgrades: UnionUpgradeRegistry<"NodeShape"> = {
  modelName: "NodeShape",
  discriminant: "shapeType",
  variants: {
    "box": "ShapeBox",
    "circle": "ShapeCircle",
  },
};

export const CanvasActivityUpgrades: UnionUpgradeRegistry<"CanvasActivity"> = {
  modelName: "CanvasActivity",
  discriminant: "activityType",
  variants: {
    "shapeAdded": "ShapeAddedActivity",
    "shapeDeleted": "ShapeDeletedActivity",
    "shapeUpdated": "ShapeUpdatedActivity",
  },
};

