/* Generated by @palantir/pack.document-schema.type-gen@0.13.0 */


import type { ShapeBox__v1, ShapeBox__v2, ShapeCircle__v1, ShapeCircle__v2 } from "./types.js";

/**
 * Typed upgrade functions the application must supply at boot. Coverage is
 * exhaustive: missing or extra entries fail type-check at the `DocumentModel(...)`
 * call site. Derived fields receive their declared source fields; required
 * additive fields receive no arguments. Optional additive fields are absent
 * — `undefined` is a legal value at the new version, so the runtime lens
 * leaves them alone.
 */
export interface DocumentUpgradeFns {
  ShapeBox: {
    v2: {
      fillColor: (oldFields: Pick<ShapeBox__v1, "color">) => ShapeBox__v2["fillColor"];
      strokeColor: (oldFields: Pick<ShapeBox__v1, "color">) => ShapeBox__v2["strokeColor"];
      opacity: () => ShapeBox__v2["opacity"];
    };
  };
  ShapeCircle: {
    v2: {
      fillColor: (oldFields: Pick<ShapeCircle__v1, "color">) => ShapeCircle__v2["fillColor"];
      strokeColor: (oldFields: Pick<ShapeCircle__v1, "color">) => ShapeCircle__v2["strokeColor"];
      opacity: () => ShapeCircle__v2["opacity"];
    };
  };
}
