/* Generated by @palantir/pack.document-schema.type-gen@0.8.0 */

import type { ZodType } from 'zod';
import { z } from 'zod';
import type { ShapeBox_v1 } from './types_v1.js';

export const ShapeBoxSchema_v1 = z.object({
  left: z.number(),
  right: z.number(),
  top: z.number(),
  bottom: z.number(),
  color: z.string().optional(),
}) satisfies ZodType<ShapeBox_v1>;
