/* Generated by @palantir/pack.document-schema.type-gen@0.8.0 */

import type { ZodType } from 'zod';
import { z } from 'zod';
import type { ShapeBox_v2 } from './types_v2.js';

export const ShapeBoxSchema_v2 = z.object({
  left: z.number(),
  right: z.number(),
  top: z.number(),
  bottom: z.number(),
  fillColor: z.string().optional(),
  strokeColor: z.string().optional(),
  opacity: z.number().optional(),
}) satisfies ZodType<ShapeBox_v2>;
