/* Generated by @palantir/pack.document-schema.type-gen@0.15.0 */

import type {
  DocumentSchema,
  RecordModel,
  UnionModel,
} from '@palantir/pack.document-schema.model-types';
import { Metadata } from '@palantir/pack.document-schema.model-types';
import type { Widget } from '../generated/custom-types.js';
import { WidgetSchema } from '../generated/custom-schema.js';

export interface WidgetModel extends RecordModel<Widget, typeof WidgetSchema> {}
export const WidgetModel: WidgetModel = {
  __type: {} as Widget,
  zodSchema: WidgetSchema,
  [Metadata]: {
    name: 'Widget',
  },
};

export const DocumentModel = {
  Widget: WidgetModel,
  [Metadata]: {
    version: 1,
  },
} as const satisfies DocumentSchema;

export type DocumentModel = typeof DocumentModel;
