/* Generated by @palantir/pack.document-schema.type-gen@0.2.0 */

import type {
  DocumentSchema,
  RecordModel,
  UnionModel,
} from '@palantir/pack.document-schema.model-types';
import { Metadata } from '@palantir/pack.document-schema.model-types';
import type { Animal, AnimalCat, AnimalDog, Cat, Dog } from './types.js';
import {
  AnimalCatSchema,
  AnimalDogSchema,
  AnimalSchema,
  CatSchema,
  DogSchema,
} from './schema.js';

export interface CatModel extends RecordModel<Cat, typeof CatSchema> {}
export const CatModel: CatModel = {
  __type: {} as Cat,
  zodSchema: CatSchema,
  [Metadata]: {
    name: 'Cat',
  },
};

export interface DogModel extends RecordModel<Dog, typeof DogSchema> {}
export const DogModel: DogModel = {
  __type: {} as Dog,
  zodSchema: DogSchema,
  [Metadata]: {
    name: 'Dog',
  },
};

export interface AnimalModel extends UnionModel<Animal, typeof AnimalSchema> {}
export const AnimalModel: AnimalModel = {
  __type: {} as Animal,
  zodSchema: AnimalSchema,
  [Metadata]: {
    discriminant: 'kind',
    name: 'Animal',
  },
};

export interface AnimalCatModel extends UnionModel<
  AnimalCat,
  typeof AnimalCatSchema
> {}
export const AnimalCatModel: AnimalCatModel = {
  __type: {} as AnimalCat,
  zodSchema: AnimalCatSchema,
  [Metadata]: {
    discriminant: 'kind',
    name: 'AnimalCat',
  },
};

export interface AnimalDogModel extends UnionModel<
  AnimalDog,
  typeof AnimalDogSchema
> {}
export const AnimalDogModel: AnimalDogModel = {
  __type: {} as AnimalDog,
  zodSchema: AnimalDogSchema,
  [Metadata]: {
    discriminant: 'kind',
    name: 'AnimalDog',
  },
};

export const DocumentModel = {
  Cat: CatModel,
  Dog: DogModel,
  Animal: AnimalModel,
  AnimalCat: AnimalCatModel,
  AnimalDog: AnimalDogModel,
  [Metadata]: {
    version: 1,
  },
} as const satisfies DocumentSchema;

export type DocumentModel = typeof DocumentModel;
