/* Generated by @palantir/pack.document-schema.type-gen@0.15.0 */

import type {
  DocumentSchema,
  RecordModel,
  UnionModel,
} from '@palantir/pack.document-schema.model-types';
import { Metadata } from '@palantir/pack.document-schema.model-types';
import type { Asset } from './types.js';
import { AssetSchema } from './schema.js';

export interface AssetModel extends RecordModel<Asset, typeof AssetSchema> {}
export const AssetModel: AssetModel = {
  __type: {} as Asset,
  zodSchema: AssetSchema,
  [Metadata]: {
    externalRefFieldTypes: {
      thumbnail: 'mediaRef',
      linkedObject: 'objectRef',
    },
    name: 'Asset',
  },
};

export const DocumentModel = {
  Asset: AssetModel,
  [Metadata]: {
    version: 1,
  },
} as const satisfies DocumentSchema;

export type DocumentModel = typeof DocumentModel;
