/* Generated by @palantir/pack.document-schema.type-gen@0.8.0 */

import type {
  MigrationRegistry,
  UnionMigrationRegistry,
} from '@palantir/pack.document-schema.model-types';

export const ShapeBoxMigrations: MigrationRegistry<'ShapeBox'> = {
  modelName: 'ShapeBox',
  allFields: {
    bottom: { type: { kind: 'primitive' } },
    color: { type: { kind: 'optional', inner: { kind: 'primitive' } } },
    fillColor: { type: { kind: 'optional', inner: { kind: 'primitive' } } },
    left: { type: { kind: 'primitive' } },
    opacity: { type: { kind: 'optional', inner: { kind: 'primitive' } } },
    right: { type: { kind: 'primitive' } },
    strokeColor: { type: { kind: 'optional', inner: { kind: 'primitive' } } },
    top: { type: { kind: 'primitive' } },
  },
  steps: [
    {
      name: 'v2',
      addedInVersion: 2,
      fields: {
        fillColor: {
          derivedFrom: [],
          forward: () => undefined,
        },
        strokeColor: {
          derivedFrom: [],
          forward: () => undefined,
        },
        opacity: {
          derivedFrom: [],
          forward: () => undefined,
        },
      },
      removedFields: ['color'],
    },
  ],
};
