/* Generated by @palantir/pack.document-schema.type-gen@0.8.0 */

/** Internal representation containing all fields across all schema versions. */
export interface ShapeBox__Internal {
  readonly bottom: number;
  readonly color?: string;
  readonly fillColor?: string;
  readonly left: number;
  readonly opacity?: number;
  readonly right: number;
  readonly strokeColor?: string;
  readonly top: number;
}
