name: Release

env:
  DO_NOT_TRACK: 1

on:
  push:
    branches:
      - main
      - release/*
      - next

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') }}
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Cache turbo build setup
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup PNPM
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8

      - name: Setup Node.js environment
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Publish packages
        run: pnpm ci:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Save publish data
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: published-packages
          path: pnpm-publish-summary.json

  # snapshot:
  #   name: Snapshot
  #   needs: release
  #   if: ${{ !failure() && !cancelled() }} # when none of the needed jobs fail or are cancelled (skipped or successful jobs are ok).
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v4

  #     - name: Setup PNPM
  #       uses: pnpm/action-setup@v4
  #       with:
  #         version: 8.7.4

  #     - name: Setup Node.js environment
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 18
  #         registry-url: 'https://registry.npmjs.org'
  #         cache: "pnpm"

  #     - name: Install dependencies
  #       run: pnpm install

  #     - name: Build code
  #       run: pnpm exec turbo run build

  #     - name: Update versions for snapshots
  #       run: pnpm exec changeset version --snapshot ${GITHUB_REF_NAME//\//__}

  #     - name: Make sure code is up to date
  #       run: pnpm exec turbo run postVersioning

  #     - name: Rebuild things
  #       run: pnpm exec turbo run build

  #     - name: Publish results
  #       run: pnpm exec changeset publish --no-git-tag --tag next-${GITHUB_REF_NAME//\//__}
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
